// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/auth.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthProof accompanies every Owned-level request. The signature is made by the
// privilege key, which is only available while an unlock session is live
// (D-18, D-19, D-30).
//
// Signed input, concatenated:
//
//	"openair-owned-v1" || target_device_id || cap_id || msg_type
//	                   || nonce || issued_at
//
// Binding to target_device_id stops a proof captured by one peer being replayed
// against another; binding to cap_id and msg_type stops a proof for a file read
// being reused to start a screen mirror.
type AuthProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`                        // 32 random bytes, fresh per request
	IssuedAt      int64                  `protobuf:"varint,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"` // unix milliseconds; verifier allows +/- 60s
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                // Ed25519
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthProof) Reset() {
	*x = AuthProof{}
	mi := &file_openair_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProof) ProtoMessage() {}

func (x *AuthProof) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProof.ProtoReflect.Descriptor instead.
func (*AuthProof) Descriptor() ([]byte, []int) {
	return file_openair_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthProof) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AuthProof) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *AuthProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Revoke narrows a peer's access, taking effect mid-session (PRD R5).
// TRUST_LEVEL_UNPAIRED additionally requires discarding both pinned keys.
type Revoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewLevel      TrustLevel             `protobuf:"varint,1,opt,name=new_level,json=newLevel,proto3,enum=openair.v1.TrustLevel" json:"new_level,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revoke) Reset() {
	*x = Revoke{}
	mi := &file_openair_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revoke) ProtoMessage() {}

func (x *Revoke) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revoke.ProtoReflect.Descriptor instead.
func (*Revoke) Descriptor() ([]byte, []int) {
	return file_openair_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Revoke) GetNewLevel() TrustLevel {
	if x != nil {
		return x.NewLevel
	}
	return TrustLevel_TRUST_LEVEL_UNSPECIFIED
}

func (x *Revoke) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CapabilityGrant widens access. Sent by the device granting it, never in
// response to a request, so a peer cannot ask to be promoted (PRD R3).
type CapabilityGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapIds        []CapabilityId         `protobuf:"varint,1,rep,packed,name=cap_ids,json=capIds,proto3,enum=openair.v1.CapabilityId" json:"cap_ids,omitempty"`
	Level         TrustLevel             `protobuf:"varint,2,opt,name=level,proto3,enum=openair.v1.TrustLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityGrant) Reset() {
	*x = CapabilityGrant{}
	mi := &file_openair_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityGrant) ProtoMessage() {}

func (x *CapabilityGrant) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityGrant.ProtoReflect.Descriptor instead.
func (*CapabilityGrant) Descriptor() ([]byte, []int) {
	return file_openair_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CapabilityGrant) GetCapIds() []CapabilityId {
	if x != nil {
		return x.CapIds
	}
	return nil
}

func (x *CapabilityGrant) GetLevel() TrustLevel {
	if x != nil {
		return x.Level
	}
	return TrustLevel_TRUST_LEVEL_UNSPECIFIED
}

// ConsentRequest asks a Trusted-level peer's user for approval (D-25).
type ConsentRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CapId     CapabilityId           `protobuf:"varint,2,opt,name=cap_id,json=capId,proto3,enum=openair.v1.CapabilityId" json:"cap_id,omitempty"`
	// Shown to the user verbatim. Implementations must not substitute a generic
	// string; it is the only thing telling them what they are approving.
	Operation      string       `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	RequestedScope ConsentScope `protobuf:"varint,4,opt,name=requested_scope,json=requestedScope,proto3,enum=openair.v1.ConsentScope" json:"requested_scope,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsentRequest) Reset() {
	*x = ConsentRequest{}
	mi := &file_openair_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentRequest) ProtoMessage() {}

func (x *ConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentRequest.ProtoReflect.Descriptor instead.
func (*ConsentRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ConsentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConsentRequest) GetCapId() CapabilityId {
	if x != nil {
		return x.CapId
	}
	return CapabilityId_CAPABILITY_ID_UNSPECIFIED
}

func (x *ConsentRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ConsentRequest) GetRequestedScope() ConsentScope {
	if x != nil {
		return x.RequestedScope
	}
	return ConsentScope_CONSENT_SCOPE_UNSPECIFIED
}

type ConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Granted       bool                   `protobuf:"varint,2,opt,name=granted,proto3" json:"granted,omitempty"`
	Scope         ConsentScope           `protobuf:"varint,3,opt,name=scope,proto3,enum=openair.v1.ConsentScope" json:"scope,omitempty"` // may narrow requested_scope, never widen it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsentResponse) Reset() {
	*x = ConsentResponse{}
	mi := &file_openair_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentResponse) ProtoMessage() {}

func (x *ConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentResponse.ProtoReflect.Descriptor instead.
func (*ConsentResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ConsentResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConsentResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *ConsentResponse) GetScope() ConsentScope {
	if x != nil {
		return x.Scope
	}
	return ConsentScope_CONSENT_SCOPE_UNSPECIFIED
}

// SessionAnnounce precedes the first Owned-level operation and any use of
// input or mirror, so the accessed device can show an indicator and log it
// (PRD R4).
type SessionAnnounce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CapIds        []CapabilityId         `protobuf:"varint,2,rep,packed,name=cap_ids,json=capIds,proto3,enum=openair.v1.CapabilityId" json:"cap_ids,omitempty"`
	Purpose       string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	OwnedLevel    bool                   `protobuf:"varint,4,opt,name=owned_level,json=ownedLevel,proto3" json:"owned_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAnnounce) Reset() {
	*x = SessionAnnounce{}
	mi := &file_openair_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAnnounce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAnnounce) ProtoMessage() {}

func (x *SessionAnnounce) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAnnounce.ProtoReflect.Descriptor instead.
func (*SessionAnnounce) Descriptor() ([]byte, []int) {
	return file_openair_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SessionAnnounce) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionAnnounce) GetCapIds() []CapabilityId {
	if x != nil {
		return x.CapIds
	}
	return nil
}

func (x *SessionAnnounce) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *SessionAnnounce) GetOwnedLevel() bool {
	if x != nil {
		return x.OwnedLevel
	}
	return false
}

// SessionAnnounceAck answers a SessionAnnounce.
//
// PROTOCOL.md §6.3 does not define one, and for a capability that runs on
// streams none is needed: the announce and the work that follows it are ordered
// by the control stream. `input` is not that -- its events are datagrams, which
// have no ordering against a stream at all, so events sent immediately after an
// announce routinely arrive before it and are discarded as unauthorised. The
// initiator therefore waits for this before its first event (D-83).
//
// It also carries the refusal that would otherwise be silent: a device that
// does not accept remote input says so here, rather than dropping every
// datagram and leaving the sender to guess.
type SessionAnnounceAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // why not, shown to the person who asked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAnnounceAck) Reset() {
	*x = SessionAnnounceAck{}
	mi := &file_openair_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAnnounceAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAnnounceAck) ProtoMessage() {}

func (x *SessionAnnounceAck) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAnnounceAck.ProtoReflect.Descriptor instead.
func (*SessionAnnounceAck) Descriptor() ([]byte, []int) {
	return file_openair_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *SessionAnnounceAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionAnnounceAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SessionAnnounceAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SessionEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEnd) Reset() {
	*x = SessionEnd{}
	mi := &file_openair_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEnd) ProtoMessage() {}

func (x *SessionEnd) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEnd.ProtoReflect.Descriptor instead.
func (*SessionEnd) Descriptor() ([]byte, []int) {
	return file_openair_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *SessionEnd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionEnd) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// SessionKill is a courtesy notification, not the enforcement. A local user
// killing a session takes effect by the accessed device refusing further
// operations and resetting streams, so a misbehaving peer cannot ignore it.
type SessionKill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionKill) Reset() {
	*x = SessionKill{}
	mi := &file_openair_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionKill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionKill) ProtoMessage() {}

func (x *SessionKill) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionKill.ProtoReflect.Descriptor instead.
func (*SessionKill) Descriptor() ([]byte, []int) {
	return file_openair_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *SessionKill) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_openair_v1_auth_proto protoreflect.FileDescriptor

const file_openair_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x15openair/v1/auth.proto\x12\n" +
	"openair.v1\x1a\x17openair/v1/common.proto\"\\\n" +
	"\tAuthProof\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1b\n" +
	"\tissued_at\x18\x02 \x01(\x03R\bissuedAt\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"U\n" +
	"\x06Revoke\x123\n" +
	"\tnew_level\x18\x01 \x01(\x0e2\x16.openair.v1.TrustLevelR\bnewLevel\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"r\n" +
	"\x0fCapabilityGrant\x121\n" +
	"\acap_ids\x18\x01 \x03(\x0e2\x18.openair.v1.CapabilityIdR\x06capIds\x12,\n" +
	"\x05level\x18\x02 \x01(\x0e2\x16.openair.v1.TrustLevelR\x05level\"\xc1\x01\n" +
	"\x0eConsentRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12/\n" +
	"\x06cap_id\x18\x02 \x01(\x0e2\x18.openair.v1.CapabilityIdR\x05capId\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12A\n" +
	"\x0frequested_scope\x18\x04 \x01(\x0e2\x18.openair.v1.ConsentScopeR\x0erequestedScope\"z\n" +
	"\x0fConsentResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\agranted\x18\x02 \x01(\bR\agranted\x12.\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x18.openair.v1.ConsentScopeR\x05scope\"\x9e\x01\n" +
	"\x0fSessionAnnounce\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x121\n" +
	"\acap_ids\x18\x02 \x03(\x0e2\x18.openair.v1.CapabilityIdR\x06capIds\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x12\x1f\n" +
	"\vowned_level\x18\x04 \x01(\bR\n" +
	"ownedLevel\"g\n" +
	"\x12SessionAnnounceAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"C\n" +
	"\n" +
	"SessionEnd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\",\n" +
	"\vSessionKill\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionIdBEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_auth_proto_rawDescOnce sync.Once
	file_openair_v1_auth_proto_rawDescData []byte
)

func file_openair_v1_auth_proto_rawDescGZIP() []byte {
	file_openair_v1_auth_proto_rawDescOnce.Do(func() {
		file_openair_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_auth_proto_rawDesc), len(file_openair_v1_auth_proto_rawDesc)))
	})
	return file_openair_v1_auth_proto_rawDescData
}

var file_openair_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_openair_v1_auth_proto_goTypes = []any{
	(*AuthProof)(nil),          // 0: openair.v1.AuthProof
	(*Revoke)(nil),             // 1: openair.v1.Revoke
	(*CapabilityGrant)(nil),    // 2: openair.v1.CapabilityGrant
	(*ConsentRequest)(nil),     // 3: openair.v1.ConsentRequest
	(*ConsentResponse)(nil),    // 4: openair.v1.ConsentResponse
	(*SessionAnnounce)(nil),    // 5: openair.v1.SessionAnnounce
	(*SessionAnnounceAck)(nil), // 6: openair.v1.SessionAnnounceAck
	(*SessionEnd)(nil),         // 7: openair.v1.SessionEnd
	(*SessionKill)(nil),        // 8: openair.v1.SessionKill
	(TrustLevel)(0),            // 9: openair.v1.TrustLevel
	(CapabilityId)(0),          // 10: openair.v1.CapabilityId
	(ConsentScope)(0),          // 11: openair.v1.ConsentScope
}
var file_openair_v1_auth_proto_depIdxs = []int32{
	9,  // 0: openair.v1.Revoke.new_level:type_name -> openair.v1.TrustLevel
	10, // 1: openair.v1.CapabilityGrant.cap_ids:type_name -> openair.v1.CapabilityId
	9,  // 2: openair.v1.CapabilityGrant.level:type_name -> openair.v1.TrustLevel
	10, // 3: openair.v1.ConsentRequest.cap_id:type_name -> openair.v1.CapabilityId
	11, // 4: openair.v1.ConsentRequest.requested_scope:type_name -> openair.v1.ConsentScope
	11, // 5: openair.v1.ConsentResponse.scope:type_name -> openair.v1.ConsentScope
	10, // 6: openair.v1.SessionAnnounce.cap_ids:type_name -> openair.v1.CapabilityId
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_openair_v1_auth_proto_init() }
func file_openair_v1_auth_proto_init() {
	if File_openair_v1_auth_proto != nil {
		return
	}
	file_openair_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_auth_proto_rawDesc), len(file_openair_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_auth_proto_goTypes,
		DependencyIndexes: file_openair_v1_auth_proto_depIdxs,
		MessageInfos:      file_openair_v1_auth_proto_msgTypes,
	}.Build()
	File_openair_v1_auth_proto = out.File
	file_openair_v1_auth_proto_goTypes = nil
	file_openair_v1_auth_proto_depIdxs = nil
}
