// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/clipboard.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClipboardMessageType int32

const (
	ClipboardMessageType_CLIPBOARD_MESSAGE_TYPE_UNSPECIFIED ClipboardMessageType = 0
	ClipboardMessageType_CLIPBOARD_MESSAGE_TYPE_PUSH        ClipboardMessageType = 1
)

// Enum value maps for ClipboardMessageType.
var (
	ClipboardMessageType_name = map[int32]string{
		0: "CLIPBOARD_MESSAGE_TYPE_UNSPECIFIED",
		1: "CLIPBOARD_MESSAGE_TYPE_PUSH",
	}
	ClipboardMessageType_value = map[string]int32{
		"CLIPBOARD_MESSAGE_TYPE_UNSPECIFIED": 0,
		"CLIPBOARD_MESSAGE_TYPE_PUSH":        1,
	}
)

func (x ClipboardMessageType) Enum() *ClipboardMessageType {
	p := new(ClipboardMessageType)
	*p = x
	return p
}

func (x ClipboardMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClipboardMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_clipboard_proto_enumTypes[0].Descriptor()
}

func (ClipboardMessageType) Type() protoreflect.EnumType {
	return &file_openair_v1_clipboard_proto_enumTypes[0]
}

func (x ClipboardMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClipboardMessageType.Descriptor instead.
func (ClipboardMessageType) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_clipboard_proto_rawDescGZIP(), []int{0}
}

// ClipboardPush is the manual path, guaranteed on every platform. Automatic
// sync is opt-in and best-effort where OS policy restricts background clipboard
// reads (PRD R19). Content must not be persisted by relays or logged in
// plaintext (PRD R20).
type ClipboardPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mime          string                 `protobuf:"bytes,1,opt,name=mime,proto3" json:"mime,omitempty"` // "text/plain; charset=utf-8" initially
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	OriginTs      int64                  `protobuf:"varint,3,opt,name=origin_ts,json=originTs,proto3" json:"origin_ts,omitempty"`
	OriginTag     string                 `protobuf:"bytes,4,opt,name=origin_tag,json=originTag,proto3" json:"origin_tag,omitempty"` // suppresses echo loops in auto-sync mode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipboardPush) Reset() {
	*x = ClipboardPush{}
	mi := &file_openair_v1_clipboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipboardPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardPush) ProtoMessage() {}

func (x *ClipboardPush) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_clipboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardPush.ProtoReflect.Descriptor instead.
func (*ClipboardPush) Descriptor() ([]byte, []int) {
	return file_openair_v1_clipboard_proto_rawDescGZIP(), []int{0}
}

func (x *ClipboardPush) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ClipboardPush) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ClipboardPush) GetOriginTs() int64 {
	if x != nil {
		return x.OriginTs
	}
	return 0
}

func (x *ClipboardPush) GetOriginTag() string {
	if x != nil {
		return x.OriginTag
	}
	return ""
}

var File_openair_v1_clipboard_proto protoreflect.FileDescriptor

const file_openair_v1_clipboard_proto_rawDesc = "" +
	"\n" +
	"\x1aopenair/v1/clipboard.proto\x12\n" +
	"openair.v1\"y\n" +
	"\rClipboardPush\x12\x12\n" +
	"\x04mime\x18\x01 \x01(\tR\x04mime\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1b\n" +
	"\torigin_ts\x18\x03 \x01(\x03R\boriginTs\x12\x1d\n" +
	"\n" +
	"origin_tag\x18\x04 \x01(\tR\toriginTag*_\n" +
	"\x14ClipboardMessageType\x12&\n" +
	"\"CLIPBOARD_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCLIPBOARD_MESSAGE_TYPE_PUSH\x10\x01BEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_clipboard_proto_rawDescOnce sync.Once
	file_openair_v1_clipboard_proto_rawDescData []byte
)

func file_openair_v1_clipboard_proto_rawDescGZIP() []byte {
	file_openair_v1_clipboard_proto_rawDescOnce.Do(func() {
		file_openair_v1_clipboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_clipboard_proto_rawDesc), len(file_openair_v1_clipboard_proto_rawDesc)))
	})
	return file_openair_v1_clipboard_proto_rawDescData
}

var file_openair_v1_clipboard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openair_v1_clipboard_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_openair_v1_clipboard_proto_goTypes = []any{
	(ClipboardMessageType)(0), // 0: openair.v1.ClipboardMessageType
	(*ClipboardPush)(nil),     // 1: openair.v1.ClipboardPush
}
var file_openair_v1_clipboard_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openair_v1_clipboard_proto_init() }
func file_openair_v1_clipboard_proto_init() {
	if File_openair_v1_clipboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_clipboard_proto_rawDesc), len(file_openair_v1_clipboard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_clipboard_proto_goTypes,
		DependencyIndexes: file_openair_v1_clipboard_proto_depIdxs,
		EnumInfos:         file_openair_v1_clipboard_proto_enumTypes,
		MessageInfos:      file_openair_v1_clipboard_proto_msgTypes,
	}.Build()
	File_openair_v1_clipboard_proto = out.File
	file_openair_v1_clipboard_proto_goTypes = nil
	file_openair_v1_clipboard_proto_depIdxs = nil
}
