// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/common.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CapabilityId enumerates the capabilities carried in the envelope's capID
// byte. See PROTOCOL.md Appendix B.
//
// Note the offset from the wire values: proto3 reserves 0 for UNSPECIFIED, so
// these constants are NOT the on-wire capID. The wire value is the enum value
// minus one. Encoders must convert.
type CapabilityId int32

const (
	CapabilityId_CAPABILITY_ID_UNSPECIFIED   CapabilityId = 0
	CapabilityId_CAPABILITY_ID_CONTROL       CapabilityId = 1 // wire 0
	CapabilityId_CAPABILITY_ID_FILES         CapabilityId = 2 // wire 1
	CapabilityId_CAPABILITY_ID_CLIPBOARD     CapabilityId = 3 // wire 2
	CapabilityId_CAPABILITY_ID_REMOTEFS      CapabilityId = 4 // wire 3
	CapabilityId_CAPABILITY_ID_NOTIFICATIONS CapabilityId = 5 // wire 4
	CapabilityId_CAPABILITY_ID_INPUT         CapabilityId = 6 // wire 5
	CapabilityId_CAPABILITY_ID_MIRROR        CapabilityId = 7 // wire 6
)

// Enum value maps for CapabilityId.
var (
	CapabilityId_name = map[int32]string{
		0: "CAPABILITY_ID_UNSPECIFIED",
		1: "CAPABILITY_ID_CONTROL",
		2: "CAPABILITY_ID_FILES",
		3: "CAPABILITY_ID_CLIPBOARD",
		4: "CAPABILITY_ID_REMOTEFS",
		5: "CAPABILITY_ID_NOTIFICATIONS",
		6: "CAPABILITY_ID_INPUT",
		7: "CAPABILITY_ID_MIRROR",
	}
	CapabilityId_value = map[string]int32{
		"CAPABILITY_ID_UNSPECIFIED":   0,
		"CAPABILITY_ID_CONTROL":       1,
		"CAPABILITY_ID_FILES":         2,
		"CAPABILITY_ID_CLIPBOARD":     3,
		"CAPABILITY_ID_REMOTEFS":      4,
		"CAPABILITY_ID_NOTIFICATIONS": 5,
		"CAPABILITY_ID_INPUT":         6,
		"CAPABILITY_ID_MIRROR":        7,
	}
)

func (x CapabilityId) Enum() *CapabilityId {
	p := new(CapabilityId)
	*p = x
	return p
}

func (x CapabilityId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapabilityId) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_common_proto_enumTypes[0].Descriptor()
}

func (CapabilityId) Type() protoreflect.EnumType {
	return &file_openair_v1_common_proto_enumTypes[0]
}

func (x CapabilityId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapabilityId.Descriptor instead.
func (CapabilityId) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_common_proto_rawDescGZIP(), []int{0}
}

// TrustLevel is the access level granted to a paired peer (PRD R3, D-20).
type TrustLevel int32

const (
	TrustLevel_TRUST_LEVEL_UNSPECIFIED TrustLevel = 0
	TrustLevel_TRUST_LEVEL_UNPAIRED    TrustLevel = 1 // revocation target: discard both pinned keys
	TrustLevel_TRUST_LEVEL_TRUSTED     TrustLevel = 2 // default at pairing; consent required
	TrustLevel_TRUST_LEVEL_OWNED       TrustLevel = 3 // unattended access, gated by the privilege key
)

// Enum value maps for TrustLevel.
var (
	TrustLevel_name = map[int32]string{
		0: "TRUST_LEVEL_UNSPECIFIED",
		1: "TRUST_LEVEL_UNPAIRED",
		2: "TRUST_LEVEL_TRUSTED",
		3: "TRUST_LEVEL_OWNED",
	}
	TrustLevel_value = map[string]int32{
		"TRUST_LEVEL_UNSPECIFIED": 0,
		"TRUST_LEVEL_UNPAIRED":    1,
		"TRUST_LEVEL_TRUSTED":     2,
		"TRUST_LEVEL_OWNED":       3,
	}
)

func (x TrustLevel) Enum() *TrustLevel {
	p := new(TrustLevel)
	*p = x
	return p
}

func (x TrustLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrustLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_common_proto_enumTypes[1].Descriptor()
}

func (TrustLevel) Type() protoreflect.EnumType {
	return &file_openair_v1_common_proto_enumTypes[1]
}

func (x TrustLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrustLevel.Descriptor instead.
func (TrustLevel) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_common_proto_rawDescGZIP(), []int{1}
}

// ProtectionTier reports how a device protects its privilege key (D-21).
// A peer at TIER_NONE must not be granted TRUST_LEVEL_OWNED.
type ProtectionTier int32

const (
	ProtectionTier_PROTECTION_TIER_UNSPECIFIED ProtectionTier = 0
	ProtectionTier_PROTECTION_TIER_KEYSTORE    ProtectionTier = 1 // platform keystore or TPM 2.0
	ProtectionTier_PROTECTION_TIER_PASSPHRASE  ProtectionTier = 2 // Argon2id over a passphrase
	ProtectionTier_PROTECTION_TIER_NONE        ProtectionTier = 3 // unprotected; Trusted only
)

// Enum value maps for ProtectionTier.
var (
	ProtectionTier_name = map[int32]string{
		0: "PROTECTION_TIER_UNSPECIFIED",
		1: "PROTECTION_TIER_KEYSTORE",
		2: "PROTECTION_TIER_PASSPHRASE",
		3: "PROTECTION_TIER_NONE",
	}
	ProtectionTier_value = map[string]int32{
		"PROTECTION_TIER_UNSPECIFIED": 0,
		"PROTECTION_TIER_KEYSTORE":    1,
		"PROTECTION_TIER_PASSPHRASE":  2,
		"PROTECTION_TIER_NONE":        3,
	}
)

func (x ProtectionTier) Enum() *ProtectionTier {
	p := new(ProtectionTier)
	*p = x
	return p
}

func (x ProtectionTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtectionTier) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_common_proto_enumTypes[2].Descriptor()
}

func (ProtectionTier) Type() protoreflect.EnumType {
	return &file_openair_v1_common_proto_enumTypes[2]
}

func (x ProtectionTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtectionTier.Descriptor instead.
func (ProtectionTier) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_common_proto_rawDescGZIP(), []int{2}
}

// ConsentScope is how long a Trusted-level approval lasts (D-25).
type ConsentScope int32

const (
	ConsentScope_CONSENT_SCOPE_UNSPECIFIED ConsentScope = 0
	ConsentScope_CONSENT_SCOPE_ONCE        ConsentScope = 1
	ConsentScope_CONSENT_SCOPE_SESSION     ConsentScope = 2
	ConsentScope_CONSENT_SCOPE_PERSISTENT  ConsentScope = 3 // recorded in the trust store, revocable
)

// Enum value maps for ConsentScope.
var (
	ConsentScope_name = map[int32]string{
		0: "CONSENT_SCOPE_UNSPECIFIED",
		1: "CONSENT_SCOPE_ONCE",
		2: "CONSENT_SCOPE_SESSION",
		3: "CONSENT_SCOPE_PERSISTENT",
	}
	ConsentScope_value = map[string]int32{
		"CONSENT_SCOPE_UNSPECIFIED": 0,
		"CONSENT_SCOPE_ONCE":        1,
		"CONSENT_SCOPE_SESSION":     2,
		"CONSENT_SCOPE_PERSISTENT":  3,
	}
)

func (x ConsentScope) Enum() *ConsentScope {
	p := new(ConsentScope)
	*p = x
	return p
}

func (x ConsentScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsentScope) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_common_proto_enumTypes[3].Descriptor()
}

func (ConsentScope) Type() protoreflect.EnumType {
	return &file_openair_v1_common_proto_enumTypes[3]
}

func (x ConsentScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsentScope.Descriptor instead.
func (ConsentScope) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_common_proto_rawDescGZIP(), []int{3}
}

// PathClass is an advisory hint about the current network path (PRD R8).
// Capabilities may adapt quality to it and must function without it.
type PathClass int32

const (
	PathClass_PATH_CLASS_UNSPECIFIED PathClass = 0
	PathClass_PATH_CLASS_LAN         PathClass = 1
	PathClass_PATH_CLASS_PUNCHED     PathClass = 2
	PathClass_PATH_CLASS_RELAYED     PathClass = 3
)

// Enum value maps for PathClass.
var (
	PathClass_name = map[int32]string{
		0: "PATH_CLASS_UNSPECIFIED",
		1: "PATH_CLASS_LAN",
		2: "PATH_CLASS_PUNCHED",
		3: "PATH_CLASS_RELAYED",
	}
	PathClass_value = map[string]int32{
		"PATH_CLASS_UNSPECIFIED": 0,
		"PATH_CLASS_LAN":         1,
		"PATH_CLASS_PUNCHED":     2,
		"PATH_CLASS_RELAYED":     3,
	}
)

func (x PathClass) Enum() *PathClass {
	p := new(PathClass)
	*p = x
	return p
}

func (x PathClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathClass) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_common_proto_enumTypes[4].Descriptor()
}

func (PathClass) Type() protoreflect.EnumType {
	return &file_openair_v1_common_proto_enumTypes[4]
}

func (x PathClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathClass.Descriptor instead.
func (PathClass) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_common_proto_rawDescGZIP(), []int{4}
}

var File_openair_v1_common_proto protoreflect.FileDescriptor

const file_openair_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x17openair/v1/common.proto\x12\n" +
	"openair.v1*\xee\x01\n" +
	"\fCapabilityId\x12\x1d\n" +
	"\x19CAPABILITY_ID_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CAPABILITY_ID_CONTROL\x10\x01\x12\x17\n" +
	"\x13CAPABILITY_ID_FILES\x10\x02\x12\x1b\n" +
	"\x17CAPABILITY_ID_CLIPBOARD\x10\x03\x12\x1a\n" +
	"\x16CAPABILITY_ID_REMOTEFS\x10\x04\x12\x1f\n" +
	"\x1bCAPABILITY_ID_NOTIFICATIONS\x10\x05\x12\x17\n" +
	"\x13CAPABILITY_ID_INPUT\x10\x06\x12\x18\n" +
	"\x14CAPABILITY_ID_MIRROR\x10\a*s\n" +
	"\n" +
	"TrustLevel\x12\x1b\n" +
	"\x17TRUST_LEVEL_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TRUST_LEVEL_UNPAIRED\x10\x01\x12\x17\n" +
	"\x13TRUST_LEVEL_TRUSTED\x10\x02\x12\x15\n" +
	"\x11TRUST_LEVEL_OWNED\x10\x03*\x89\x01\n" +
	"\x0eProtectionTier\x12\x1f\n" +
	"\x1bPROTECTION_TIER_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PROTECTION_TIER_KEYSTORE\x10\x01\x12\x1e\n" +
	"\x1aPROTECTION_TIER_PASSPHRASE\x10\x02\x12\x18\n" +
	"\x14PROTECTION_TIER_NONE\x10\x03*~\n" +
	"\fConsentScope\x12\x1d\n" +
	"\x19CONSENT_SCOPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONSENT_SCOPE_ONCE\x10\x01\x12\x19\n" +
	"\x15CONSENT_SCOPE_SESSION\x10\x02\x12\x1c\n" +
	"\x18CONSENT_SCOPE_PERSISTENT\x10\x03*k\n" +
	"\tPathClass\x12\x1a\n" +
	"\x16PATH_CLASS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePATH_CLASS_LAN\x10\x01\x12\x16\n" +
	"\x12PATH_CLASS_PUNCHED\x10\x02\x12\x16\n" +
	"\x12PATH_CLASS_RELAYED\x10\x03BEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_common_proto_rawDescOnce sync.Once
	file_openair_v1_common_proto_rawDescData []byte
)

func file_openair_v1_common_proto_rawDescGZIP() []byte {
	file_openair_v1_common_proto_rawDescOnce.Do(func() {
		file_openair_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_common_proto_rawDesc), len(file_openair_v1_common_proto_rawDesc)))
	})
	return file_openair_v1_common_proto_rawDescData
}

var file_openair_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_openair_v1_common_proto_goTypes = []any{
	(CapabilityId)(0),   // 0: openair.v1.CapabilityId
	(TrustLevel)(0),     // 1: openair.v1.TrustLevel
	(ProtectionTier)(0), // 2: openair.v1.ProtectionTier
	(ConsentScope)(0),   // 3: openair.v1.ConsentScope
	(PathClass)(0),      // 4: openair.v1.PathClass
}
var file_openair_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openair_v1_common_proto_init() }
func file_openair_v1_common_proto_init() {
	if File_openair_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_common_proto_rawDesc), len(file_openair_v1_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_common_proto_goTypes,
		DependencyIndexes: file_openair_v1_common_proto_depIdxs,
		EnumInfos:         file_openair_v1_common_proto_enumTypes,
	}.Build()
	File_openair_v1_common_proto = out.File
	file_openair_v1_common_proto_goTypes = nil
	file_openair_v1_common_proto_depIdxs = nil
}
