// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/daemon.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The daemon control plane (capID 7). These messages never travel between
// devices: they are what a local shell -- the CLI, a tray UI -- says to
// `openaird` over a unix socket or named pipe. D-29 reuses the session envelope
// (PROTOCOL.md §3) for that link rather than adding gRPC, so this file is the
// message set that envelope carries, and nothing else changes.
//
// The envelope has no request ID, so every request and every response carries
// one: the initiator allocates, the responder echoes. Prompts run the other way
// -- the daemon asks a subscribed client -- and are correlated the same way in
// their own namespace, which is unambiguous because the message type already
// says which direction a frame is travelling.
type DaemonMessageType int32

const (
	DaemonMessageType_DAEMON_MESSAGE_TYPE_UNSPECIFIED          DaemonMessageType = 0
	DaemonMessageType_DAEMON_MESSAGE_TYPE_STATUS_REQUEST       DaemonMessageType = 1
	DaemonMessageType_DAEMON_MESSAGE_TYPE_STATUS_RESPONSE      DaemonMessageType = 2
	DaemonMessageType_DAEMON_MESSAGE_TYPE_DEVICE_LIST_REQUEST  DaemonMessageType = 3
	DaemonMessageType_DAEMON_MESSAGE_TYPE_DEVICE_LIST_RESPONSE DaemonMessageType = 4
	DaemonMessageType_DAEMON_MESSAGE_TYPE_SEND_REQUEST         DaemonMessageType = 5
	DaemonMessageType_DAEMON_MESSAGE_TYPE_SEND_RESPONSE        DaemonMessageType = 6
	DaemonMessageType_DAEMON_MESSAGE_TYPE_PAIR_REQUEST         DaemonMessageType = 7
	DaemonMessageType_DAEMON_MESSAGE_TYPE_PAIR_RESPONSE        DaemonMessageType = 8
	DaemonMessageType_DAEMON_MESSAGE_TYPE_SUBSCRIBE_REQUEST    DaemonMessageType = 9
	DaemonMessageType_DAEMON_MESSAGE_TYPE_SUBSCRIBE_RESPONSE   DaemonMessageType = 10
	DaemonMessageType_DAEMON_MESSAGE_TYPE_EVENT                DaemonMessageType = 11
	DaemonMessageType_DAEMON_MESSAGE_TYPE_PROMPT               DaemonMessageType = 12
	DaemonMessageType_DAEMON_MESSAGE_TYPE_PROMPT_RESPONSE      DaemonMessageType = 13
	DaemonMessageType_DAEMON_MESSAGE_TYPE_CLIPBOARD_REQUEST    DaemonMessageType = 14
	DaemonMessageType_DAEMON_MESSAGE_TYPE_CLIPBOARD_RESPONSE   DaemonMessageType = 15
	DaemonMessageType_DAEMON_MESSAGE_TYPE_ERROR                DaemonMessageType = 16
)

// Enum value maps for DaemonMessageType.
var (
	DaemonMessageType_name = map[int32]string{
		0:  "DAEMON_MESSAGE_TYPE_UNSPECIFIED",
		1:  "DAEMON_MESSAGE_TYPE_STATUS_REQUEST",
		2:  "DAEMON_MESSAGE_TYPE_STATUS_RESPONSE",
		3:  "DAEMON_MESSAGE_TYPE_DEVICE_LIST_REQUEST",
		4:  "DAEMON_MESSAGE_TYPE_DEVICE_LIST_RESPONSE",
		5:  "DAEMON_MESSAGE_TYPE_SEND_REQUEST",
		6:  "DAEMON_MESSAGE_TYPE_SEND_RESPONSE",
		7:  "DAEMON_MESSAGE_TYPE_PAIR_REQUEST",
		8:  "DAEMON_MESSAGE_TYPE_PAIR_RESPONSE",
		9:  "DAEMON_MESSAGE_TYPE_SUBSCRIBE_REQUEST",
		10: "DAEMON_MESSAGE_TYPE_SUBSCRIBE_RESPONSE",
		11: "DAEMON_MESSAGE_TYPE_EVENT",
		12: "DAEMON_MESSAGE_TYPE_PROMPT",
		13: "DAEMON_MESSAGE_TYPE_PROMPT_RESPONSE",
		14: "DAEMON_MESSAGE_TYPE_CLIPBOARD_REQUEST",
		15: "DAEMON_MESSAGE_TYPE_CLIPBOARD_RESPONSE",
		16: "DAEMON_MESSAGE_TYPE_ERROR",
	}
	DaemonMessageType_value = map[string]int32{
		"DAEMON_MESSAGE_TYPE_UNSPECIFIED":          0,
		"DAEMON_MESSAGE_TYPE_STATUS_REQUEST":       1,
		"DAEMON_MESSAGE_TYPE_STATUS_RESPONSE":      2,
		"DAEMON_MESSAGE_TYPE_DEVICE_LIST_REQUEST":  3,
		"DAEMON_MESSAGE_TYPE_DEVICE_LIST_RESPONSE": 4,
		"DAEMON_MESSAGE_TYPE_SEND_REQUEST":         5,
		"DAEMON_MESSAGE_TYPE_SEND_RESPONSE":        6,
		"DAEMON_MESSAGE_TYPE_PAIR_REQUEST":         7,
		"DAEMON_MESSAGE_TYPE_PAIR_RESPONSE":        8,
		"DAEMON_MESSAGE_TYPE_SUBSCRIBE_REQUEST":    9,
		"DAEMON_MESSAGE_TYPE_SUBSCRIBE_RESPONSE":   10,
		"DAEMON_MESSAGE_TYPE_EVENT":                11,
		"DAEMON_MESSAGE_TYPE_PROMPT":               12,
		"DAEMON_MESSAGE_TYPE_PROMPT_RESPONSE":      13,
		"DAEMON_MESSAGE_TYPE_CLIPBOARD_REQUEST":    14,
		"DAEMON_MESSAGE_TYPE_CLIPBOARD_RESPONSE":   15,
		"DAEMON_MESSAGE_TYPE_ERROR":                16,
	}
)

func (x DaemonMessageType) Enum() *DaemonMessageType {
	p := new(DaemonMessageType)
	*p = x
	return p
}

func (x DaemonMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DaemonMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_daemon_proto_enumTypes[0].Descriptor()
}

func (DaemonMessageType) Type() protoreflect.EnumType {
	return &file_openair_v1_daemon_proto_enumTypes[0]
}

func (x DaemonMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DaemonMessageType.Descriptor instead.
func (DaemonMessageType) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type DaemonEventKind int32

const (
	DaemonEventKind_DAEMON_EVENT_KIND_UNSPECIFIED       DaemonEventKind = 0
	DaemonEventKind_DAEMON_EVENT_KIND_DEVICE_FOUND      DaemonEventKind = 1
	DaemonEventKind_DAEMON_EVENT_KIND_DEVICE_LOST       DaemonEventKind = 2
	DaemonEventKind_DAEMON_EVENT_KIND_SESSION_OPEN      DaemonEventKind = 3
	DaemonEventKind_DAEMON_EVENT_KIND_SESSION_CLOSED    DaemonEventKind = 4
	DaemonEventKind_DAEMON_EVENT_KIND_TRANSFER_STARTED  DaemonEventKind = 5
	DaemonEventKind_DAEMON_EVENT_KIND_TRANSFER_PROGRESS DaemonEventKind = 6
	DaemonEventKind_DAEMON_EVENT_KIND_TRANSFER_DONE     DaemonEventKind = 7
	DaemonEventKind_DAEMON_EVENT_KIND_PAIRED            DaemonEventKind = 8
	DaemonEventKind_DAEMON_EVENT_KIND_REFUSED           DaemonEventKind = 9
	DaemonEventKind_DAEMON_EVENT_KIND_CLIPBOARD         DaemonEventKind = 10
)

// Enum value maps for DaemonEventKind.
var (
	DaemonEventKind_name = map[int32]string{
		0:  "DAEMON_EVENT_KIND_UNSPECIFIED",
		1:  "DAEMON_EVENT_KIND_DEVICE_FOUND",
		2:  "DAEMON_EVENT_KIND_DEVICE_LOST",
		3:  "DAEMON_EVENT_KIND_SESSION_OPEN",
		4:  "DAEMON_EVENT_KIND_SESSION_CLOSED",
		5:  "DAEMON_EVENT_KIND_TRANSFER_STARTED",
		6:  "DAEMON_EVENT_KIND_TRANSFER_PROGRESS",
		7:  "DAEMON_EVENT_KIND_TRANSFER_DONE",
		8:  "DAEMON_EVENT_KIND_PAIRED",
		9:  "DAEMON_EVENT_KIND_REFUSED",
		10: "DAEMON_EVENT_KIND_CLIPBOARD",
	}
	DaemonEventKind_value = map[string]int32{
		"DAEMON_EVENT_KIND_UNSPECIFIED":       0,
		"DAEMON_EVENT_KIND_DEVICE_FOUND":      1,
		"DAEMON_EVENT_KIND_DEVICE_LOST":       2,
		"DAEMON_EVENT_KIND_SESSION_OPEN":      3,
		"DAEMON_EVENT_KIND_SESSION_CLOSED":    4,
		"DAEMON_EVENT_KIND_TRANSFER_STARTED":  5,
		"DAEMON_EVENT_KIND_TRANSFER_PROGRESS": 6,
		"DAEMON_EVENT_KIND_TRANSFER_DONE":     7,
		"DAEMON_EVENT_KIND_PAIRED":            8,
		"DAEMON_EVENT_KIND_REFUSED":           9,
		"DAEMON_EVENT_KIND_CLIPBOARD":         10,
	}
)

func (x DaemonEventKind) Enum() *DaemonEventKind {
	p := new(DaemonEventKind)
	*p = x
	return p
}

func (x DaemonEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DaemonEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_daemon_proto_enumTypes[1].Descriptor()
}

func (DaemonEventKind) Type() protoreflect.EnumType {
	return &file_openair_v1_daemon_proto_enumTypes[1]
}

func (x DaemonEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DaemonEventKind.Descriptor instead.
func (DaemonEventKind) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{1}
}

type DaemonPromptKind int32

const (
	DaemonPromptKind_DAEMON_PROMPT_KIND_UNSPECIFIED     DaemonPromptKind = 0
	DaemonPromptKind_DAEMON_PROMPT_KIND_PAIR_SAS        DaemonPromptKind = 1 // compare six digits (§5.2)
	DaemonPromptKind_DAEMON_PROMPT_KIND_ACCEPT_TRANSFER DaemonPromptKind = 2
)

// Enum value maps for DaemonPromptKind.
var (
	DaemonPromptKind_name = map[int32]string{
		0: "DAEMON_PROMPT_KIND_UNSPECIFIED",
		1: "DAEMON_PROMPT_KIND_PAIR_SAS",
		2: "DAEMON_PROMPT_KIND_ACCEPT_TRANSFER",
	}
	DaemonPromptKind_value = map[string]int32{
		"DAEMON_PROMPT_KIND_UNSPECIFIED":     0,
		"DAEMON_PROMPT_KIND_PAIR_SAS":        1,
		"DAEMON_PROMPT_KIND_ACCEPT_TRANSFER": 2,
	}
)

func (x DaemonPromptKind) Enum() *DaemonPromptKind {
	p := new(DaemonPromptKind)
	*p = x
	return p
}

func (x DaemonPromptKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DaemonPromptKind) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_daemon_proto_enumTypes[2].Descriptor()
}

func (DaemonPromptKind) Type() protoreflect.EnumType {
	return &file_openair_v1_daemon_proto_enumTypes[2]
}

func (x DaemonPromptKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DaemonPromptKind.Descriptor instead.
func (DaemonPromptKind) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{2}
}

// DaemonStatusRequest asks what the daemon is and what it is doing.
type DaemonStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonStatusRequest) Reset() {
	*x = DaemonStatusRequest{}
	mi := &file_openair_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatusRequest) ProtoMessage() {}

func (x *DaemonStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatusRequest.ProtoReflect.Descriptor instead.
func (*DaemonStatusRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *DaemonStatusRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type DaemonStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DeviceId       string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Platform       string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	ListenAddr     string                 `protobuf:"bytes,5,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"` // the QUIC address actually bound
	DestDir        string                 `protobuf:"bytes,6,opt,name=dest_dir,json=destDir,proto3" json:"dest_dir,omitempty"`          // where inbound files land
	StartedUnix    int64                  `protobuf:"varint,7,opt,name=started_unix,json=startedUnix,proto3" json:"started_unix,omitempty"`
	PairedDevices  uint32                 `protobuf:"varint,8,opt,name=paired_devices,json=pairedDevices,proto3" json:"paired_devices,omitempty"`
	ActiveSessions uint32                 `protobuf:"varint,9,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	Announcing     bool                   `protobuf:"varint,10,opt,name=announcing,proto3" json:"announcing,omitempty"`                   // advertising on the LAN (M3)
	AutoAccept     bool                   `protobuf:"varint,11,opt,name=auto_accept,json=autoAccept,proto3" json:"auto_accept,omitempty"` // inbound transfers accepted without a prompt
	Subscribers    uint32                 `protobuf:"varint,12,opt,name=subscribers,proto3" json:"subscribers,omitempty"`                 // clients currently able to answer a prompt
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DaemonStatusResponse) Reset() {
	*x = DaemonStatusResponse{}
	mi := &file_openair_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatusResponse) ProtoMessage() {}

func (x *DaemonStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatusResponse.ProtoReflect.Descriptor instead.
func (*DaemonStatusResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *DaemonStatusResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonStatusResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DaemonStatusResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DaemonStatusResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DaemonStatusResponse) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *DaemonStatusResponse) GetDestDir() string {
	if x != nil {
		return x.DestDir
	}
	return ""
}

func (x *DaemonStatusResponse) GetStartedUnix() int64 {
	if x != nil {
		return x.StartedUnix
	}
	return 0
}

func (x *DaemonStatusResponse) GetPairedDevices() uint32 {
	if x != nil {
		return x.PairedDevices
	}
	return 0
}

func (x *DaemonStatusResponse) GetActiveSessions() uint32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *DaemonStatusResponse) GetAnnouncing() bool {
	if x != nil {
		return x.Announcing
	}
	return false
}

func (x *DaemonStatusResponse) GetAutoAccept() bool {
	if x != nil {
		return x.AutoAccept
	}
	return false
}

func (x *DaemonStatusResponse) GetSubscribers() uint32 {
	if x != nil {
		return x.Subscribers
	}
	return 0
}

// DaemonDeviceListRequest lists what the daemon can see: paired devices from
// the trust store, and unpaired ones discovery has heard from.
type DaemonDeviceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PairedOnly    bool                   `protobuf:"varint,2,opt,name=paired_only,json=pairedOnly,proto3" json:"paired_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonDeviceListRequest) Reset() {
	*x = DaemonDeviceListRequest{}
	mi := &file_openair_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonDeviceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonDeviceListRequest) ProtoMessage() {}

func (x *DaemonDeviceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonDeviceListRequest.ProtoReflect.Descriptor instead.
func (*DaemonDeviceListRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *DaemonDeviceListRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonDeviceListRequest) GetPairedOnly() bool {
	if x != nil {
		return x.PairedOnly
	}
	return false
}

type DaemonDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Addrs         []string               `protobuf:"bytes,4,rep,name=addrs,proto3" json:"addrs,omitempty"` // discovery candidates; empty if not seen
	Paired        bool                   `protobuf:"varint,5,opt,name=paired,proto3" json:"paired,omitempty"`
	Level         TrustLevel             `protobuf:"varint,6,opt,name=level,proto3,enum=openair.v1.TrustLevel" json:"level,omitempty"`
	SessionOpen   bool                   `protobuf:"varint,7,opt,name=session_open,json=sessionOpen,proto3" json:"session_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonDevice) Reset() {
	*x = DaemonDevice{}
	mi := &file_openair_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonDevice) ProtoMessage() {}

func (x *DaemonDevice) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonDevice.ProtoReflect.Descriptor instead.
func (*DaemonDevice) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *DaemonDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DaemonDevice) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DaemonDevice) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DaemonDevice) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *DaemonDevice) GetPaired() bool {
	if x != nil {
		return x.Paired
	}
	return false
}

func (x *DaemonDevice) GetLevel() TrustLevel {
	if x != nil {
		return x.Level
	}
	return TrustLevel_TRUST_LEVEL_UNSPECIFIED
}

func (x *DaemonDevice) GetSessionOpen() bool {
	if x != nil {
		return x.SessionOpen
	}
	return false
}

type DaemonDeviceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Devices       []*DaemonDevice        `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonDeviceListResponse) Reset() {
	*x = DaemonDeviceListResponse{}
	mi := &file_openair_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonDeviceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonDeviceListResponse) ProtoMessage() {}

func (x *DaemonDeviceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonDeviceListResponse.ProtoReflect.Descriptor instead.
func (*DaemonDeviceListResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *DaemonDeviceListResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonDeviceListResponse) GetDevices() []*DaemonDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

// DaemonSendRequest offers local files to a device, named or at an explicit
// host:port. The response returns once the transfer completes, because a CLI
// that returns early cannot report a digest mismatch.
type DaemonSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // device name, DeviceID prefix, or host:port
	Paths         []string               `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonSendRequest) Reset() {
	*x = DaemonSendRequest{}
	mi := &file_openair_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonSendRequest) ProtoMessage() {}

func (x *DaemonSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonSendRequest.ProtoReflect.Descriptor instead.
func (*DaemonSendRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *DaemonSendRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonSendRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DaemonSendRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DaemonSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TransferId    string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonSendResponse) Reset() {
	*x = DaemonSendResponse{}
	mi := &file_openair_v1_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonSendResponse) ProtoMessage() {}

func (x *DaemonSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonSendResponse.ProtoReflect.Descriptor instead.
func (*DaemonSendResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *DaemonSendResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonSendResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *DaemonSendResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// DaemonPairRequest runs PROTOCOL.md §5 through the daemon. An empty offer
// means "display ours and wait"; a non-empty one means "consume this". Either
// way the six digits come back to the client as a prompt, because §5.2 forbids
// a path that does not show them.
type DaemonPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Offer         string                 `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonPairRequest) Reset() {
	*x = DaemonPairRequest{}
	mi := &file_openair_v1_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonPairRequest) ProtoMessage() {}

func (x *DaemonPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonPairRequest.ProtoReflect.Descriptor instead.
func (*DaemonPairRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *DaemonPairRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonPairRequest) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

func (x *DaemonPairRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type DaemonPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Offer         string                 `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"` // set on the displaying side, before the peer arrives
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonPairResponse) Reset() {
	*x = DaemonPairResponse{}
	mi := &file_openair_v1_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonPairResponse) ProtoMessage() {}

func (x *DaemonPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonPairResponse.ProtoReflect.Descriptor instead.
func (*DaemonPairResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *DaemonPairResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonPairResponse) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

func (x *DaemonPairResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DaemonPairResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// DaemonSubscribeRequest turns this connection into an event sink. A client
// that also answers prompts is what lets the daemon ask a human about an
// inbound transfer; with no such client, daemon policy decides alone.
type DaemonSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Prompts       bool                   `protobuf:"varint,2,opt,name=prompts,proto3" json:"prompts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonSubscribeRequest) Reset() {
	*x = DaemonSubscribeRequest{}
	mi := &file_openair_v1_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonSubscribeRequest) ProtoMessage() {}

func (x *DaemonSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonSubscribeRequest.ProtoReflect.Descriptor instead.
func (*DaemonSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *DaemonSubscribeRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonSubscribeRequest) GetPrompts() bool {
	if x != nil {
		return x.Prompts
	}
	return false
}

type DaemonSubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonSubscribeResponse) Reset() {
	*x = DaemonSubscribeResponse{}
	mi := &file_openair_v1_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonSubscribeResponse) ProtoMessage() {}

func (x *DaemonSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonSubscribeResponse.ProtoReflect.Descriptor instead.
func (*DaemonSubscribeResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *DaemonSubscribeResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// DaemonEvent is unsolicited: request_id is the request it belongs to when one
// asked for it, and zero otherwise.
type DaemonEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Kind          DaemonEventKind        `protobuf:"varint,2,opt,name=kind,proto3,enum=openair.v1.DaemonEventKind" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TransferId    string                 `protobuf:"bytes,5,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	BytesDone     uint64                 `protobuf:"varint,6,opt,name=bytes_done,json=bytesDone,proto3" json:"bytes_done,omitempty"`
	BytesTotal    uint64                 `protobuf:"varint,7,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	Ok            bool                   `protobuf:"varint,8,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonEvent) Reset() {
	*x = DaemonEvent{}
	mi := &file_openair_v1_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonEvent) ProtoMessage() {}

func (x *DaemonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonEvent.ProtoReflect.Descriptor instead.
func (*DaemonEvent) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *DaemonEvent) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonEvent) GetKind() DaemonEventKind {
	if x != nil {
		return x.Kind
	}
	return DaemonEventKind_DAEMON_EVENT_KIND_UNSPECIFIED
}

func (x *DaemonEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DaemonEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DaemonEvent) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *DaemonEvent) GetBytesDone() uint64 {
	if x != nil {
		return x.BytesDone
	}
	return 0
}

func (x *DaemonEvent) GetBytesTotal() uint64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *DaemonEvent) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// DaemonPrompt travels daemon -> client and requires an answer. request_id is
// allocated by the daemon.
type DaemonPrompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Kind          DaemonPromptKind       `protobuf:"varint,2,opt,name=kind,proto3,enum=openair.v1.DaemonPromptKind" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	Sas           string                 `protobuf:"bytes,7,opt,name=sas,proto3" json:"sas,omitempty"`     // PAIR_SAS only
	Files         []string               `protobuf:"bytes,8,rep,name=files,proto3" json:"files,omitempty"` // ACCEPT_TRANSFER only
	TotalBytes    uint64                 `protobuf:"varint,9,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonPrompt) Reset() {
	*x = DaemonPrompt{}
	mi := &file_openair_v1_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonPrompt) ProtoMessage() {}

func (x *DaemonPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonPrompt.ProtoReflect.Descriptor instead.
func (*DaemonPrompt) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *DaemonPrompt) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonPrompt) GetKind() DaemonPromptKind {
	if x != nil {
		return x.Kind
	}
	return DaemonPromptKind_DAEMON_PROMPT_KIND_UNSPECIFIED
}

func (x *DaemonPrompt) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DaemonPrompt) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DaemonPrompt) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DaemonPrompt) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DaemonPrompt) GetSas() string {
	if x != nil {
		return x.Sas
	}
	return ""
}

func (x *DaemonPrompt) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DaemonPrompt) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type DaemonPromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Approve       bool                   `protobuf:"varint,2,opt,name=approve,proto3" json:"approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonPromptResponse) Reset() {
	*x = DaemonPromptResponse{}
	mi := &file_openair_v1_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonPromptResponse) ProtoMessage() {}

func (x *DaemonPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonPromptResponse.ProtoReflect.Descriptor instead.
func (*DaemonPromptResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *DaemonPromptResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonPromptResponse) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

// DaemonClipboardRequest carries the network message verbatim (§9). That is the
// point of D-29: a tray UI pushing the clipboard emits the same bytes the wire
// carries, so there is no translation layer to keep in sync.
type DaemonClipboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Push          *ClipboardPush         `protobuf:"bytes,3,opt,name=push,proto3" json:"push,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonClipboardRequest) Reset() {
	*x = DaemonClipboardRequest{}
	mi := &file_openair_v1_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonClipboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonClipboardRequest) ProtoMessage() {}

func (x *DaemonClipboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonClipboardRequest.ProtoReflect.Descriptor instead.
func (*DaemonClipboardRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *DaemonClipboardRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonClipboardRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DaemonClipboardRequest) GetPush() *ClipboardPush {
	if x != nil {
		return x.Push
	}
	return nil
}

type DaemonClipboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonClipboardResponse) Reset() {
	*x = DaemonClipboardResponse{}
	mi := &file_openair_v1_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonClipboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonClipboardResponse) ProtoMessage() {}

func (x *DaemonClipboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonClipboardResponse.ProtoReflect.Descriptor instead.
func (*DaemonClipboardResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *DaemonClipboardResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// DaemonError is the failure reply to any request. code is a PROTOCOL.md §10
// value where one applies and zero where the failure is local.
type DaemonError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonError) Reset() {
	*x = DaemonError{}
	mi := &file_openair_v1_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonError) ProtoMessage() {}

func (x *DaemonError) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonError.ProtoReflect.Descriptor instead.
func (*DaemonError) Descriptor() ([]byte, []int) {
	return file_openair_v1_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *DaemonError) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DaemonError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DaemonError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_openair_v1_daemon_proto protoreflect.FileDescriptor

const file_openair_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x17openair/v1/daemon.proto\x12\n" +
	"openair.v1\x1a\x1aopenair/v1/clipboard.proto\x1a\x17openair/v1/common.proto\"4\n" +
	"\x13DaemonStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"\xa3\x03\n" +
	"\x14DaemonStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1f\n" +
	"\vlisten_addr\x18\x05 \x01(\tR\n" +
	"listenAddr\x12\x19\n" +
	"\bdest_dir\x18\x06 \x01(\tR\adestDir\x12!\n" +
	"\fstarted_unix\x18\a \x01(\x03R\vstartedUnix\x12%\n" +
	"\x0epaired_devices\x18\b \x01(\rR\rpairedDevices\x12'\n" +
	"\x0factive_sessions\x18\t \x01(\rR\x0eactiveSessions\x12\x1e\n" +
	"\n" +
	"announcing\x18\n" +
	" \x01(\bR\n" +
	"announcing\x12\x1f\n" +
	"\vauto_accept\x18\v \x01(\bR\n" +
	"autoAccept\x12 \n" +
	"\vsubscribers\x18\f \x01(\rR\vsubscribers\"Y\n" +
	"\x17DaemonDeviceListRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1f\n" +
	"\vpaired_only\x18\x02 \x01(\bR\n" +
	"pairedOnly\"\xe9\x01\n" +
	"\fDaemonDevice\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x14\n" +
	"\x05addrs\x18\x04 \x03(\tR\x05addrs\x12\x16\n" +
	"\x06paired\x18\x05 \x01(\bR\x06paired\x12,\n" +
	"\x05level\x18\x06 \x01(\x0e2\x16.openair.v1.TrustLevelR\x05level\x12!\n" +
	"\fsession_open\x18\a \x01(\bR\vsessionOpen\"m\n" +
	"\x18DaemonDeviceListResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x122\n" +
	"\adevices\x18\x02 \x03(\v2\x18.openair.v1.DaemonDeviceR\adevices\"`\n" +
	"\x11DaemonSendRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x14\n" +
	"\x05paths\x18\x03 \x03(\tR\x05paths\"q\n" +
	"\x12DaemonSendResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"g\n" +
	"\x11DaemonPairRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x14\n" +
	"\x05offer\x18\x02 \x01(\tR\x05offer\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\"\x89\x01\n" +
	"\x12DaemonPairResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x14\n" +
	"\x05offer\x18\x02 \x01(\tR\x05offer\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\"Q\n" +
	"\x16DaemonSubscribeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x18\n" +
	"\aprompts\x18\x02 \x01(\bR\aprompts\"8\n" +
	"\x17DaemonSubscribeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"\xff\x01\n" +
	"\vDaemonEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.openair.v1.DaemonEventKindR\x04kind\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vtransfer_id\x18\x05 \x01(\tR\n" +
	"transferId\x12\x1d\n" +
	"\n" +
	"bytes_done\x18\x06 \x01(\x04R\tbytesDone\x12\x1f\n" +
	"\vbytes_total\x18\a \x01(\x04R\n" +
	"bytesTotal\x12\x0e\n" +
	"\x02ok\x18\b \x01(\bR\x02ok\"\x98\x02\n" +
	"\fDaemonPrompt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x120\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1c.openair.v1.DaemonPromptKindR\x04kind\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\x12\x10\n" +
	"\x03sas\x18\a \x01(\tR\x03sas\x12\x14\n" +
	"\x05files\x18\b \x03(\tR\x05files\x12\x1f\n" +
	"\vtotal_bytes\x18\t \x01(\x04R\n" +
	"totalBytes\"O\n" +
	"\x14DaemonPromptResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x18\n" +
	"\aapprove\x18\x02 \x01(\bR\aapprove\"~\n" +
	"\x16DaemonClipboardRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12-\n" +
	"\x04push\x18\x03 \x01(\v2\x19.openair.v1.ClipboardPushR\x04push\"8\n" +
	"\x17DaemonClipboardResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"Z\n" +
	"\vDaemonError\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*\xb3\x05\n" +
	"\x11DaemonMessageType\x12#\n" +
	"\x1fDAEMON_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"DAEMON_MESSAGE_TYPE_STATUS_REQUEST\x10\x01\x12'\n" +
	"#DAEMON_MESSAGE_TYPE_STATUS_RESPONSE\x10\x02\x12+\n" +
	"'DAEMON_MESSAGE_TYPE_DEVICE_LIST_REQUEST\x10\x03\x12,\n" +
	"(DAEMON_MESSAGE_TYPE_DEVICE_LIST_RESPONSE\x10\x04\x12$\n" +
	" DAEMON_MESSAGE_TYPE_SEND_REQUEST\x10\x05\x12%\n" +
	"!DAEMON_MESSAGE_TYPE_SEND_RESPONSE\x10\x06\x12$\n" +
	" DAEMON_MESSAGE_TYPE_PAIR_REQUEST\x10\a\x12%\n" +
	"!DAEMON_MESSAGE_TYPE_PAIR_RESPONSE\x10\b\x12)\n" +
	"%DAEMON_MESSAGE_TYPE_SUBSCRIBE_REQUEST\x10\t\x12*\n" +
	"&DAEMON_MESSAGE_TYPE_SUBSCRIBE_RESPONSE\x10\n" +
	"\x12\x1d\n" +
	"\x19DAEMON_MESSAGE_TYPE_EVENT\x10\v\x12\x1e\n" +
	"\x1aDAEMON_MESSAGE_TYPE_PROMPT\x10\f\x12'\n" +
	"#DAEMON_MESSAGE_TYPE_PROMPT_RESPONSE\x10\r\x12)\n" +
	"%DAEMON_MESSAGE_TYPE_CLIPBOARD_REQUEST\x10\x0e\x12*\n" +
	"&DAEMON_MESSAGE_TYPE_CLIPBOARD_RESPONSE\x10\x0f\x12\x1d\n" +
	"\x19DAEMON_MESSAGE_TYPE_ERROR\x10\x10*\x99\x03\n" +
	"\x0fDaemonEventKind\x12!\n" +
	"\x1dDAEMON_EVENT_KIND_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDAEMON_EVENT_KIND_DEVICE_FOUND\x10\x01\x12!\n" +
	"\x1dDAEMON_EVENT_KIND_DEVICE_LOST\x10\x02\x12\"\n" +
	"\x1eDAEMON_EVENT_KIND_SESSION_OPEN\x10\x03\x12$\n" +
	" DAEMON_EVENT_KIND_SESSION_CLOSED\x10\x04\x12&\n" +
	"\"DAEMON_EVENT_KIND_TRANSFER_STARTED\x10\x05\x12'\n" +
	"#DAEMON_EVENT_KIND_TRANSFER_PROGRESS\x10\x06\x12#\n" +
	"\x1fDAEMON_EVENT_KIND_TRANSFER_DONE\x10\a\x12\x1c\n" +
	"\x18DAEMON_EVENT_KIND_PAIRED\x10\b\x12\x1d\n" +
	"\x19DAEMON_EVENT_KIND_REFUSED\x10\t\x12\x1f\n" +
	"\x1bDAEMON_EVENT_KIND_CLIPBOARD\x10\n" +
	"*\x7f\n" +
	"\x10DaemonPromptKind\x12\"\n" +
	"\x1eDAEMON_PROMPT_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDAEMON_PROMPT_KIND_PAIR_SAS\x10\x01\x12&\n" +
	"\"DAEMON_PROMPT_KIND_ACCEPT_TRANSFER\x10\x02BEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_daemon_proto_rawDescOnce sync.Once
	file_openair_v1_daemon_proto_rawDescData []byte
)

func file_openair_v1_daemon_proto_rawDescGZIP() []byte {
	file_openair_v1_daemon_proto_rawDescOnce.Do(func() {
		file_openair_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_daemon_proto_rawDesc), len(file_openair_v1_daemon_proto_rawDesc)))
	})
	return file_openair_v1_daemon_proto_rawDescData
}

var file_openair_v1_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_openair_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_openair_v1_daemon_proto_goTypes = []any{
	(DaemonMessageType)(0),           // 0: openair.v1.DaemonMessageType
	(DaemonEventKind)(0),             // 1: openair.v1.DaemonEventKind
	(DaemonPromptKind)(0),            // 2: openair.v1.DaemonPromptKind
	(*DaemonStatusRequest)(nil),      // 3: openair.v1.DaemonStatusRequest
	(*DaemonStatusResponse)(nil),     // 4: openair.v1.DaemonStatusResponse
	(*DaemonDeviceListRequest)(nil),  // 5: openair.v1.DaemonDeviceListRequest
	(*DaemonDevice)(nil),             // 6: openair.v1.DaemonDevice
	(*DaemonDeviceListResponse)(nil), // 7: openair.v1.DaemonDeviceListResponse
	(*DaemonSendRequest)(nil),        // 8: openair.v1.DaemonSendRequest
	(*DaemonSendResponse)(nil),       // 9: openair.v1.DaemonSendResponse
	(*DaemonPairRequest)(nil),        // 10: openair.v1.DaemonPairRequest
	(*DaemonPairResponse)(nil),       // 11: openair.v1.DaemonPairResponse
	(*DaemonSubscribeRequest)(nil),   // 12: openair.v1.DaemonSubscribeRequest
	(*DaemonSubscribeResponse)(nil),  // 13: openair.v1.DaemonSubscribeResponse
	(*DaemonEvent)(nil),              // 14: openair.v1.DaemonEvent
	(*DaemonPrompt)(nil),             // 15: openair.v1.DaemonPrompt
	(*DaemonPromptResponse)(nil),     // 16: openair.v1.DaemonPromptResponse
	(*DaemonClipboardRequest)(nil),   // 17: openair.v1.DaemonClipboardRequest
	(*DaemonClipboardResponse)(nil),  // 18: openair.v1.DaemonClipboardResponse
	(*DaemonError)(nil),              // 19: openair.v1.DaemonError
	(TrustLevel)(0),                  // 20: openair.v1.TrustLevel
	(*ClipboardPush)(nil),            // 21: openair.v1.ClipboardPush
}
var file_openair_v1_daemon_proto_depIdxs = []int32{
	20, // 0: openair.v1.DaemonDevice.level:type_name -> openair.v1.TrustLevel
	6,  // 1: openair.v1.DaemonDeviceListResponse.devices:type_name -> openair.v1.DaemonDevice
	1,  // 2: openair.v1.DaemonEvent.kind:type_name -> openair.v1.DaemonEventKind
	2,  // 3: openair.v1.DaemonPrompt.kind:type_name -> openair.v1.DaemonPromptKind
	21, // 4: openair.v1.DaemonClipboardRequest.push:type_name -> openair.v1.ClipboardPush
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_openair_v1_daemon_proto_init() }
func file_openair_v1_daemon_proto_init() {
	if File_openair_v1_daemon_proto != nil {
		return
	}
	file_openair_v1_clipboard_proto_init()
	file_openair_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_daemon_proto_rawDesc), len(file_openair_v1_daemon_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_daemon_proto_goTypes,
		DependencyIndexes: file_openair_v1_daemon_proto_depIdxs,
		EnumInfos:         file_openair_v1_daemon_proto_enumTypes,
		MessageInfos:      file_openair_v1_daemon_proto_msgTypes,
	}.Build()
	File_openair_v1_daemon_proto = out.File
	file_openair_v1_daemon_proto_goTypes = nil
	file_openair_v1_daemon_proto_depIdxs = nil
}
