// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/files.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilesMessageType int32

const (
	FilesMessageType_FILES_MESSAGE_TYPE_UNSPECIFIED       FilesMessageType = 0
	FilesMessageType_FILES_MESSAGE_TYPE_TRANSFER_OFFER    FilesMessageType = 1
	FilesMessageType_FILES_MESSAGE_TYPE_TRANSFER_ACCEPT   FilesMessageType = 2
	FilesMessageType_FILES_MESSAGE_TYPE_STREAM_INIT       FilesMessageType = 3
	FilesMessageType_FILES_MESSAGE_TYPE_CHUNK_MANIFEST    FilesMessageType = 4
	FilesMessageType_FILES_MESSAGE_TYPE_TRANSFER_COMPLETE FilesMessageType = 5
	FilesMessageType_FILES_MESSAGE_TYPE_TRANSFER_CANCEL   FilesMessageType = 6
	FilesMessageType_FILES_MESSAGE_TYPE_TRANSFER_PROGRESS FilesMessageType = 7
)

// Enum value maps for FilesMessageType.
var (
	FilesMessageType_name = map[int32]string{
		0: "FILES_MESSAGE_TYPE_UNSPECIFIED",
		1: "FILES_MESSAGE_TYPE_TRANSFER_OFFER",
		2: "FILES_MESSAGE_TYPE_TRANSFER_ACCEPT",
		3: "FILES_MESSAGE_TYPE_STREAM_INIT",
		4: "FILES_MESSAGE_TYPE_CHUNK_MANIFEST",
		5: "FILES_MESSAGE_TYPE_TRANSFER_COMPLETE",
		6: "FILES_MESSAGE_TYPE_TRANSFER_CANCEL",
		7: "FILES_MESSAGE_TYPE_TRANSFER_PROGRESS",
	}
	FilesMessageType_value = map[string]int32{
		"FILES_MESSAGE_TYPE_UNSPECIFIED":       0,
		"FILES_MESSAGE_TYPE_TRANSFER_OFFER":    1,
		"FILES_MESSAGE_TYPE_TRANSFER_ACCEPT":   2,
		"FILES_MESSAGE_TYPE_STREAM_INIT":       3,
		"FILES_MESSAGE_TYPE_CHUNK_MANIFEST":    4,
		"FILES_MESSAGE_TYPE_TRANSFER_COMPLETE": 5,
		"FILES_MESSAGE_TYPE_TRANSFER_CANCEL":   6,
		"FILES_MESSAGE_TYPE_TRANSFER_PROGRESS": 7,
	}
)

func (x FilesMessageType) Enum() *FilesMessageType {
	p := new(FilesMessageType)
	*p = x
	return p
}

func (x FilesMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilesMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_files_proto_enumTypes[0].Descriptor()
}

func (FilesMessageType) Type() protoreflect.EnumType {
	return &file_openair_v1_files_proto_enumTypes[0]
}

func (x FilesMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilesMessageType.Descriptor instead.
func (FilesMessageType) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_files_proto_rawDescGZIP(), []int{0}
}

type TransferOffer struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TransferId string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // random, 16 bytes base32
	Files      []*FileMeta            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	TotalBytes uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Data streams the sender intends to open. Measurement (D-13, D-33) shows
	// more streams never help QUIC and cost 2.2x on Windows at four; senders
	// should default to one or two and treat higher values as a tuning escape.
	StreamCount   uint32 `protobuf:"varint,4,opt,name=stream_count,json=streamCount,proto3" json:"stream_count,omitempty"`
	ChunkSize     uint64 `protobuf:"varint,5,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOffer) Reset() {
	*x = TransferOffer{}
	mi := &file_openair_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOffer) ProtoMessage() {}

func (x *TransferOffer) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOffer.ProtoReflect.Descriptor instead.
func (*TransferOffer) Descriptor() ([]byte, []int) {
	return file_openair_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *TransferOffer) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferOffer) GetFiles() []*FileMeta {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *TransferOffer) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *TransferOffer) GetStreamCount() uint32 {
	if x != nil {
		return x.StreamCount
	}
	return 0
}

func (x *TransferOffer) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type FileMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative, forward slashes. Receivers must reject absolute paths, any
	// component equal to "..", and anything resolving outside the destination
	// root. Path traversal is the obvious attack on a file transfer protocol.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedAt    int64  `protobuf:"varint,3,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	Sha256        []byte `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"` // whole-file digest; empty if not computed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_openair_v1_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_openair_v1_files_proto_rawDescGZIP(), []int{1}
}

func (x *FileMeta) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMeta) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMeta) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *FileMeta) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

type TransferAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	HaveChunks    []uint64               `protobuf:"varint,3,rep,packed,name=have_chunks,json=haveChunks,proto3" json:"have_chunks,omitempty"` // verified chunk indices, for resume
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferAccept) Reset() {
	*x = TransferAccept{}
	mi := &file_openair_v1_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAccept) ProtoMessage() {}

func (x *TransferAccept) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAccept.ProtoReflect.Descriptor instead.
func (*TransferAccept) Descriptor() ([]byte, []int) {
	return file_openair_v1_files_proto_rawDescGZIP(), []int{2}
}

func (x *TransferAccept) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferAccept) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TransferAccept) GetHaveChunks() []uint64 {
	if x != nil {
		return x.HaveChunks
	}
	return nil
}

// StreamInit is the single enveloped message opening a data stream. Everything
// after it on that stream is raw chunk frames -- a 12-byte header
// (uint64 offset, uint32 size, little-endian) followed by the data, inherited
// byte-for-byte from v1.0. Chunk data is deliberately not protobuf.
type StreamInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInit) Reset() {
	*x = StreamInit{}
	mi := &file_openair_v1_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInit) ProtoMessage() {}

func (x *StreamInit) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInit.ProtoReflect.Descriptor instead.
func (*StreamInit) Descriptor() ([]byte, []int) {
	return file_openair_v1_files_proto_rawDescGZIP(), []int{3}
}

func (x *StreamInit) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

// ChunkManifest carries the per-chunk digests. They live here rather than in
// the chunk frame so the hot path stays 12 bytes.
type ChunkManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	ChunkSize     uint64                 `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkSha256   [][]byte               `protobuf:"bytes,3,rep,name=chunk_sha256,json=chunkSha256,proto3" json:"chunk_sha256,omitempty"` // 32 bytes each, in order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkManifest) Reset() {
	*x = ChunkManifest{}
	mi := &file_openair_v1_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkManifest) ProtoMessage() {}

func (x *ChunkManifest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkManifest.ProtoReflect.Descriptor instead.
func (*ChunkManifest) Descriptor() ([]byte, []int) {
	return file_openair_v1_files_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkManifest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *ChunkManifest) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *ChunkManifest) GetChunkSha256() [][]byte {
	if x != nil {
		return x.ChunkSha256
	}
	return nil
}

type TransferComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	FailedChunks  []uint64               `protobuf:"varint,3,rep,packed,name=failed_chunks,json=failedChunks,proto3" json:"failed_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferComplete) Reset() {
	*x = TransferComplete{}
	mi := &file_openair_v1_files_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferComplete) ProtoMessage() {}

func (x *TransferComplete) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_files_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferComplete.ProtoReflect.Descriptor instead.
func (*TransferComplete) Descriptor() ([]byte, []int) {
	return file_openair_v1_files_proto_rawDescGZIP(), []int{5}
}

func (x *TransferComplete) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferComplete) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TransferComplete) GetFailedChunks() []uint64 {
	if x != nil {
		return x.FailedChunks
	}
	return nil
}

type TransferCancel struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TransferId string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Reason     string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Default false: partial data and the verified-chunk set are kept, because a
	// cancel on a flaky link is usually a prelude to retrying.
	DiscardPartial bool `protobuf:"varint,3,opt,name=discard_partial,json=discardPartial,proto3" json:"discard_partial,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferCancel) Reset() {
	*x = TransferCancel{}
	mi := &file_openair_v1_files_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCancel) ProtoMessage() {}

func (x *TransferCancel) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_files_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCancel.ProtoReflect.Descriptor instead.
func (*TransferCancel) Descriptor() ([]byte, []int) {
	return file_openair_v1_files_proto_rawDescGZIP(), []int{6}
}

func (x *TransferCancel) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TransferCancel) GetDiscardPartial() bool {
	if x != nil {
		return x.DiscardPartial
	}
	return false
}

type TransferProgress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	BytesReceived  uint64                 `protobuf:"varint,2,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	ChunksVerified uint64                 `protobuf:"varint,3,opt,name=chunks_verified,json=chunksVerified,proto3" json:"chunks_verified,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferProgress) Reset() {
	*x = TransferProgress{}
	mi := &file_openair_v1_files_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferProgress) ProtoMessage() {}

func (x *TransferProgress) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_files_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferProgress.ProtoReflect.Descriptor instead.
func (*TransferProgress) Descriptor() ([]byte, []int) {
	return file_openair_v1_files_proto_rawDescGZIP(), []int{7}
}

func (x *TransferProgress) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferProgress) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *TransferProgress) GetChunksVerified() uint64 {
	if x != nil {
		return x.ChunksVerified
	}
	return 0
}

var File_openair_v1_files_proto protoreflect.FileDescriptor

const file_openair_v1_files_proto_rawDesc = "" +
	"\n" +
	"\x16openair/v1/files.proto\x12\n" +
	"openair.v1\"\xbf\x01\n" +
	"\rTransferOffer\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12*\n" +
	"\x05files\x18\x02 \x03(\v2\x14.openair.v1.FileMetaR\x05files\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12!\n" +
	"\fstream_count\x18\x04 \x01(\rR\vstreamCount\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x05 \x01(\x04R\tchunkSize\"k\n" +
	"\bFileMeta\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1f\n" +
	"\vmodified_at\x18\x03 \x01(\x03R\n" +
	"modifiedAt\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256\"n\n" +
	"\x0eTransferAccept\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x1f\n" +
	"\vhave_chunks\x18\x03 \x03(\x04R\n" +
	"haveChunks\"-\n" +
	"\n" +
	"StreamInit\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"r\n" +
	"\rChunkManifest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\x04R\tchunkSize\x12!\n" +
	"\fchunk_sha256\x18\x03 \x03(\fR\vchunkSha256\"h\n" +
	"\x10TransferComplete\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12#\n" +
	"\rfailed_chunks\x18\x03 \x03(\x04R\ffailedChunks\"r\n" +
	"\x0eTransferCancel\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0fdiscard_partial\x18\x03 \x01(\bR\x0ediscardPartial\"\x83\x01\n" +
	"\x10TransferProgress\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12%\n" +
	"\x0ebytes_received\x18\x02 \x01(\x04R\rbytesReceived\x12'\n" +
	"\x0fchunks_verified\x18\x03 \x01(\x04R\x0echunksVerified*\xcc\x02\n" +
	"\x10FilesMessageType\x12\"\n" +
	"\x1eFILES_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!FILES_MESSAGE_TYPE_TRANSFER_OFFER\x10\x01\x12&\n" +
	"\"FILES_MESSAGE_TYPE_TRANSFER_ACCEPT\x10\x02\x12\"\n" +
	"\x1eFILES_MESSAGE_TYPE_STREAM_INIT\x10\x03\x12%\n" +
	"!FILES_MESSAGE_TYPE_CHUNK_MANIFEST\x10\x04\x12(\n" +
	"$FILES_MESSAGE_TYPE_TRANSFER_COMPLETE\x10\x05\x12&\n" +
	"\"FILES_MESSAGE_TYPE_TRANSFER_CANCEL\x10\x06\x12(\n" +
	"$FILES_MESSAGE_TYPE_TRANSFER_PROGRESS\x10\aBEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_files_proto_rawDescOnce sync.Once
	file_openair_v1_files_proto_rawDescData []byte
)

func file_openair_v1_files_proto_rawDescGZIP() []byte {
	file_openair_v1_files_proto_rawDescOnce.Do(func() {
		file_openair_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_files_proto_rawDesc), len(file_openair_v1_files_proto_rawDesc)))
	})
	return file_openair_v1_files_proto_rawDescData
}

var file_openair_v1_files_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openair_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_openair_v1_files_proto_goTypes = []any{
	(FilesMessageType)(0),    // 0: openair.v1.FilesMessageType
	(*TransferOffer)(nil),    // 1: openair.v1.TransferOffer
	(*FileMeta)(nil),         // 2: openair.v1.FileMeta
	(*TransferAccept)(nil),   // 3: openair.v1.TransferAccept
	(*StreamInit)(nil),       // 4: openair.v1.StreamInit
	(*ChunkManifest)(nil),    // 5: openair.v1.ChunkManifest
	(*TransferComplete)(nil), // 6: openair.v1.TransferComplete
	(*TransferCancel)(nil),   // 7: openair.v1.TransferCancel
	(*TransferProgress)(nil), // 8: openair.v1.TransferProgress
}
var file_openair_v1_files_proto_depIdxs = []int32{
	2, // 0: openair.v1.TransferOffer.files:type_name -> openair.v1.FileMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_openair_v1_files_proto_init() }
func file_openair_v1_files_proto_init() {
	if File_openair_v1_files_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_files_proto_rawDesc), len(file_openair_v1_files_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_files_proto_goTypes,
		DependencyIndexes: file_openair_v1_files_proto_depIdxs,
		EnumInfos:         file_openair_v1_files_proto_enumTypes,
		MessageInfos:      file_openair_v1_files_proto_msgTypes,
	}.Build()
	File_openair_v1_files_proto = out.File
	file_openair_v1_files_proto_goTypes = nil
	file_openair_v1_files_proto_depIdxs = nil
}
