// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/flow.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QuiesceRequest asks the peer to throttle bulk transfer while a
// high-bandwidth capability runs. Priority is enforced here, above the
// transport, because quic-go exposes no stream prioritisation (D-24).
//
// The party that throttles is the sender of the bulk data, which is not
// necessarily the party starting the high-bandwidth capability -- which is why
// this is a wire message rather than local policy.
type QuiesceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Zero means stop entirely. Implementations should send a non-zero floor: a
	// multi-hour mirror session would otherwise stall a large transfer for hours.
	FloorBytesPerSec uint32 `protobuf:"varint,1,opt,name=floor_bytes_per_sec,json=floorBytesPerSec,proto3" json:"floor_bytes_per_sec,omitempty"`
	Reason           string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // human-readable, for the session log
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QuiesceRequest) Reset() {
	*x = QuiesceRequest{}
	mi := &file_openair_v1_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuiesceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuiesceRequest) ProtoMessage() {}

func (x *QuiesceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuiesceRequest.ProtoReflect.Descriptor instead.
func (*QuiesceRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_flow_proto_rawDescGZIP(), []int{0}
}

func (x *QuiesceRequest) GetFloorBytesPerSec() uint32 {
	if x != nil {
		return x.FloorBytesPerSec
	}
	return 0
}

func (x *QuiesceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type QuiesceRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuiesceRelease) Reset() {
	*x = QuiesceRelease{}
	mi := &file_openair_v1_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuiesceRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuiesceRelease) ProtoMessage() {}

func (x *QuiesceRelease) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuiesceRelease.ProtoReflect.Descriptor instead.
func (*QuiesceRelease) Descriptor() ([]byte, []int) {
	return file_openair_v1_flow_proto_rawDescGZIP(), []int{1}
}

// PathInfo is advisory. Capabilities may adapt quality to it and must remain
// functional without it -- capability parity across paths is required, quality
// parity is not (PRD R8).
type PathInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RttMs             uint32                 `protobuf:"varint,1,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	BandwidthBytesSec uint64                 `protobuf:"varint,2,opt,name=bandwidth_bytes_sec,json=bandwidthBytesSec,proto3" json:"bandwidth_bytes_sec,omitempty"`
	PathClass         PathClass              `protobuf:"varint,3,opt,name=path_class,json=pathClass,proto3,enum=openair.v1.PathClass" json:"path_class,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PathInfo) Reset() {
	*x = PathInfo{}
	mi := &file_openair_v1_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathInfo) ProtoMessage() {}

func (x *PathInfo) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathInfo.ProtoReflect.Descriptor instead.
func (*PathInfo) Descriptor() ([]byte, []int) {
	return file_openair_v1_flow_proto_rawDescGZIP(), []int{2}
}

func (x *PathInfo) GetRttMs() uint32 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *PathInfo) GetBandwidthBytesSec() uint64 {
	if x != nil {
		return x.BandwidthBytesSec
	}
	return 0
}

func (x *PathInfo) GetPathClass() PathClass {
	if x != nil {
		return x.PathClass
	}
	return PathClass_PATH_CLASS_UNSPECIFIED
}

var File_openair_v1_flow_proto protoreflect.FileDescriptor

const file_openair_v1_flow_proto_rawDesc = "" +
	"\n" +
	"\x15openair/v1/flow.proto\x12\n" +
	"openair.v1\x1a\x17openair/v1/common.proto\"W\n" +
	"\x0eQuiesceRequest\x12-\n" +
	"\x13floor_bytes_per_sec\x18\x01 \x01(\rR\x10floorBytesPerSec\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x10\n" +
	"\x0eQuiesceRelease\"\x87\x01\n" +
	"\bPathInfo\x12\x15\n" +
	"\x06rtt_ms\x18\x01 \x01(\rR\x05rttMs\x12.\n" +
	"\x13bandwidth_bytes_sec\x18\x02 \x01(\x04R\x11bandwidthBytesSec\x124\n" +
	"\n" +
	"path_class\x18\x03 \x01(\x0e2\x15.openair.v1.PathClassR\tpathClassBEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_flow_proto_rawDescOnce sync.Once
	file_openair_v1_flow_proto_rawDescData []byte
)

func file_openair_v1_flow_proto_rawDescGZIP() []byte {
	file_openair_v1_flow_proto_rawDescOnce.Do(func() {
		file_openair_v1_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_flow_proto_rawDesc), len(file_openair_v1_flow_proto_rawDesc)))
	})
	return file_openair_v1_flow_proto_rawDescData
}

var file_openair_v1_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_openair_v1_flow_proto_goTypes = []any{
	(*QuiesceRequest)(nil), // 0: openair.v1.QuiesceRequest
	(*QuiesceRelease)(nil), // 1: openair.v1.QuiesceRelease
	(*PathInfo)(nil),       // 2: openair.v1.PathInfo
	(PathClass)(0),         // 3: openair.v1.PathClass
}
var file_openair_v1_flow_proto_depIdxs = []int32{
	3, // 0: openair.v1.PathInfo.path_class:type_name -> openair.v1.PathClass
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_openair_v1_flow_proto_init() }
func file_openair_v1_flow_proto_init() {
	if File_openair_v1_flow_proto != nil {
		return
	}
	file_openair_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_flow_proto_rawDesc), len(file_openair_v1_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_flow_proto_goTypes,
		DependencyIndexes: file_openair_v1_flow_proto_depIdxs,
		MessageInfos:      file_openair_v1_flow_proto_msgTypes,
	}.Build()
	File_openair_v1_flow_proto = out.File
	file_openair_v1_flow_proto_goTypes = nil
	file_openair_v1_flow_proto_depIdxs = nil
}
