// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/infra.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InfraMessageType enumerates the messages carried on a rendezvous or relay
// control connection. PROTOCOL.md gives these messages no msgType because they
// are not capability messages and ride no envelope; this enum is that
// enumeration, and the framing is specified in §16 (D-62).
type InfraMessageType int32

const (
	InfraMessageType_INFRA_MESSAGE_TYPE_UNSPECIFIED     InfraMessageType = 0
	InfraMessageType_INFRA_MESSAGE_TYPE_REGISTER        InfraMessageType = 1
	InfraMessageType_INFRA_MESSAGE_TYPE_REGISTER_ACK    InfraMessageType = 2
	InfraMessageType_INFRA_MESSAGE_TYPE_LOOKUP_REQUEST  InfraMessageType = 3
	InfraMessageType_INFRA_MESSAGE_TYPE_LOOKUP_RESPONSE InfraMessageType = 4
	InfraMessageType_INFRA_MESSAGE_TYPE_RELAY_HELLO     InfraMessageType = 5
	InfraMessageType_INFRA_MESSAGE_TYPE_RELAY_CHALLENGE InfraMessageType = 6
	InfraMessageType_INFRA_MESSAGE_TYPE_RELAY_AUTH      InfraMessageType = 7
	InfraMessageType_INFRA_MESSAGE_TYPE_RELAY_AUTH_OK   InfraMessageType = 8
	InfraMessageType_INFRA_MESSAGE_TYPE_ERROR           InfraMessageType = 9
)

// Enum value maps for InfraMessageType.
var (
	InfraMessageType_name = map[int32]string{
		0: "INFRA_MESSAGE_TYPE_UNSPECIFIED",
		1: "INFRA_MESSAGE_TYPE_REGISTER",
		2: "INFRA_MESSAGE_TYPE_REGISTER_ACK",
		3: "INFRA_MESSAGE_TYPE_LOOKUP_REQUEST",
		4: "INFRA_MESSAGE_TYPE_LOOKUP_RESPONSE",
		5: "INFRA_MESSAGE_TYPE_RELAY_HELLO",
		6: "INFRA_MESSAGE_TYPE_RELAY_CHALLENGE",
		7: "INFRA_MESSAGE_TYPE_RELAY_AUTH",
		8: "INFRA_MESSAGE_TYPE_RELAY_AUTH_OK",
		9: "INFRA_MESSAGE_TYPE_ERROR",
	}
	InfraMessageType_value = map[string]int32{
		"INFRA_MESSAGE_TYPE_UNSPECIFIED":     0,
		"INFRA_MESSAGE_TYPE_REGISTER":        1,
		"INFRA_MESSAGE_TYPE_REGISTER_ACK":    2,
		"INFRA_MESSAGE_TYPE_LOOKUP_REQUEST":  3,
		"INFRA_MESSAGE_TYPE_LOOKUP_RESPONSE": 4,
		"INFRA_MESSAGE_TYPE_RELAY_HELLO":     5,
		"INFRA_MESSAGE_TYPE_RELAY_CHALLENGE": 6,
		"INFRA_MESSAGE_TYPE_RELAY_AUTH":      7,
		"INFRA_MESSAGE_TYPE_RELAY_AUTH_OK":   8,
		"INFRA_MESSAGE_TYPE_ERROR":           9,
	}
)

func (x InfraMessageType) Enum() *InfraMessageType {
	p := new(InfraMessageType)
	*p = x
	return p
}

func (x InfraMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InfraMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_infra_proto_enumTypes[0].Descriptor()
}

func (InfraMessageType) Type() protoreflect.EnumType {
	return &file_openair_v1_infra_proto_enumTypes[0]
}

func (x InfraMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InfraMessageType.Descriptor instead.
func (InfraMessageType) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{0}
}

// RegistrationAck answers a Register. expires_at is the server's own view of
// when the entry lapses, which may be earlier than the client asked for: §16
// caps it at ten minutes and the client heartbeats against this value rather
// than against what it requested.
type RegistrationAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAt     int64                  `protobuf:"varint,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationAck) Reset() {
	*x = RegistrationAck{}
	mi := &file_openair_v1_infra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationAck) ProtoMessage() {}

func (x *RegistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_infra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationAck.ProtoReflect.Descriptor instead.
func (*RegistrationAck) Descriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationAck) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// InfraError is the failure reply on a rendezvous or relay control connection.
// It carries no PROTOCOL.md §10 code: those describe a session, and these
// messages are spoken to a server that holds none.
type InfraError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfraError) Reset() {
	*x = InfraError{}
	mi := &file_openair_v1_infra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfraError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfraError) ProtoMessage() {}

func (x *InfraError) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_infra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfraError.ProtoReflect.Descriptor instead.
func (*InfraError) Descriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{1}
}

func (x *InfraError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Registration maps a DeviceID to its current endpoints (PRD R7). The server
// must verify the signature before storing, so only the key holder can move a
// device's endpoints, and must reject expiries more than 10 minutes out.
//
// Signed input:
//
//	"openair-rendezvous-v1" || device_id || endpoints (in order)
//	                        || relay_home || issued_at || expires_at
type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Endpoints     []string               `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"` // "ip:port", reflexive and local
	RelayHome     string                 `protobuf:"bytes,3,opt,name=relay_home,json=relayHome,proto3" json:"relay_home,omitempty"`
	IssuedAt      int64                  `protobuf:"varint,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 by the identity key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_openair_v1_infra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_infra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{2}
}

func (x *Registration) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Registration) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Registration) GetRelayHome() string {
	if x != nil {
		return x.RelayHome
	}
	return ""
}

func (x *Registration) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *Registration) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Registration) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_openair_v1_infra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_infra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{3}
}

func (x *LookupRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *Registration          `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_openair_v1_infra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_infra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{4}
}

func (x *LookupResponse) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *LookupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Relay authentication. The relay forwards ciphertext and holds no keys; it
// learns which DeviceIDs talk to each other, when, and how much, but not what.
type RelayHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayHello) Reset() {
	*x = RelayHello{}
	mi := &file_openair_v1_infra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayHello) ProtoMessage() {}

func (x *RelayHello) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_infra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayHello.ProtoReflect.Descriptor instead.
func (*RelayHello) Descriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{5}
}

func (x *RelayHello) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RelayHello) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type RelayChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerNonce   []byte                 `protobuf:"bytes,1,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayChallenge) Reset() {
	*x = RelayChallenge{}
	mi := &file_openair_v1_infra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayChallenge) ProtoMessage() {}

func (x *RelayChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_infra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayChallenge.ProtoReflect.Descriptor instead.
func (*RelayChallenge) Descriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{6}
}

func (x *RelayChallenge) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

type RelayAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"` // Ed25519 over both nonces
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayAuth) Reset() {
	*x = RelayAuth{}
	mi := &file_openair_v1_infra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayAuth) ProtoMessage() {}

func (x *RelayAuth) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_infra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayAuth.ProtoReflect.Descriptor instead.
func (*RelayAuth) Descriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{7}
}

func (x *RelayAuth) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// PunchRequest and PunchReady coordinate simultaneous UDP hole punching,
// signalled over the rendezvous server or an existing relay session.
type PunchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetDeviceId string                 `protobuf:"bytes,1,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"`
	Candidates     []string               `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	PunchToken     []byte                 `protobuf:"bytes,3,opt,name=punch_token,json=punchToken,proto3" json:"punch_token,omitempty"` // 16 random bytes, echoed to correlate attempts
	// Both sides begin spraying at this instant, within about 50 ms. This is what
	// makes symmetric-NAT traversal work often enough to matter.
	StartAt       int64 `protobuf:"varint,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PunchRequest) Reset() {
	*x = PunchRequest{}
	mi := &file_openair_v1_infra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchRequest) ProtoMessage() {}

func (x *PunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_infra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchRequest.ProtoReflect.Descriptor instead.
func (*PunchRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{8}
}

func (x *PunchRequest) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

func (x *PunchRequest) GetCandidates() []string {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *PunchRequest) GetPunchToken() []byte {
	if x != nil {
		return x.PunchToken
	}
	return nil
}

func (x *PunchRequest) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

type PunchReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []string               `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	PunchToken    []byte                 `protobuf:"bytes,2,opt,name=punch_token,json=punchToken,proto3" json:"punch_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PunchReady) Reset() {
	*x = PunchReady{}
	mi := &file_openair_v1_infra_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchReady) ProtoMessage() {}

func (x *PunchReady) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_infra_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchReady.ProtoReflect.Descriptor instead.
func (*PunchReady) Descriptor() ([]byte, []int) {
	return file_openair_v1_infra_proto_rawDescGZIP(), []int{9}
}

func (x *PunchReady) GetCandidates() []string {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *PunchReady) GetPunchToken() []byte {
	if x != nil {
		return x.PunchToken
	}
	return nil
}

var File_openair_v1_infra_proto protoreflect.FileDescriptor

const file_openair_v1_infra_proto_rawDesc = "" +
	"\n" +
	"\x16openair/v1/infra.proto\x12\n" +
	"openair.v1\"0\n" +
	"\x0fRegistrationAck\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\x03R\texpiresAt\"&\n" +
	"\n" +
	"InfraError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc2\x01\n" +
	"\fRegistration\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\tendpoints\x18\x02 \x03(\tR\tendpoints\x12\x1d\n" +
	"\n" +
	"relay_home\x18\x03 \x01(\tR\trelayHome\x12\x1b\n" +
	"\tissued_at\x18\x04 \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\",\n" +
	"\rLookupRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"d\n" +
	"\x0eLookupResponse\x12<\n" +
	"\fregistration\x18\x01 \x01(\v2\x18.openair.v1.RegistrationR\fregistration\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"?\n" +
	"\n" +
	"RelayHello\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\"3\n" +
	"\x0eRelayChallenge\x12!\n" +
	"\fserver_nonce\x18\x01 \x01(\fR\vserverNonce\")\n" +
	"\tRelayAuth\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"\x94\x01\n" +
	"\fPunchRequest\x12(\n" +
	"\x10target_device_id\x18\x01 \x01(\tR\x0etargetDeviceId\x12\x1e\n" +
	"\n" +
	"candidates\x18\x02 \x03(\tR\n" +
	"candidates\x12\x1f\n" +
	"\vpunch_token\x18\x03 \x01(\fR\n" +
	"punchToken\x12\x19\n" +
	"\bstart_at\x18\x04 \x01(\x03R\astartAt\"M\n" +
	"\n" +
	"PunchReady\x12\x1e\n" +
	"\n" +
	"candidates\x18\x01 \x03(\tR\n" +
	"candidates\x12\x1f\n" +
	"\vpunch_token\x18\x02 \x01(\fR\n" +
	"punchToken*\xfe\x02\n" +
	"\x10InfraMessageType\x12\"\n" +
	"\x1eINFRA_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bINFRA_MESSAGE_TYPE_REGISTER\x10\x01\x12#\n" +
	"\x1fINFRA_MESSAGE_TYPE_REGISTER_ACK\x10\x02\x12%\n" +
	"!INFRA_MESSAGE_TYPE_LOOKUP_REQUEST\x10\x03\x12&\n" +
	"\"INFRA_MESSAGE_TYPE_LOOKUP_RESPONSE\x10\x04\x12\"\n" +
	"\x1eINFRA_MESSAGE_TYPE_RELAY_HELLO\x10\x05\x12&\n" +
	"\"INFRA_MESSAGE_TYPE_RELAY_CHALLENGE\x10\x06\x12!\n" +
	"\x1dINFRA_MESSAGE_TYPE_RELAY_AUTH\x10\a\x12$\n" +
	" INFRA_MESSAGE_TYPE_RELAY_AUTH_OK\x10\b\x12\x1c\n" +
	"\x18INFRA_MESSAGE_TYPE_ERROR\x10\tBEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_infra_proto_rawDescOnce sync.Once
	file_openair_v1_infra_proto_rawDescData []byte
)

func file_openair_v1_infra_proto_rawDescGZIP() []byte {
	file_openair_v1_infra_proto_rawDescOnce.Do(func() {
		file_openair_v1_infra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_infra_proto_rawDesc), len(file_openair_v1_infra_proto_rawDesc)))
	})
	return file_openair_v1_infra_proto_rawDescData
}

var file_openair_v1_infra_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openair_v1_infra_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_openair_v1_infra_proto_goTypes = []any{
	(InfraMessageType)(0),   // 0: openair.v1.InfraMessageType
	(*RegistrationAck)(nil), // 1: openair.v1.RegistrationAck
	(*InfraError)(nil),      // 2: openair.v1.InfraError
	(*Registration)(nil),    // 3: openair.v1.Registration
	(*LookupRequest)(nil),   // 4: openair.v1.LookupRequest
	(*LookupResponse)(nil),  // 5: openair.v1.LookupResponse
	(*RelayHello)(nil),      // 6: openair.v1.RelayHello
	(*RelayChallenge)(nil),  // 7: openair.v1.RelayChallenge
	(*RelayAuth)(nil),       // 8: openair.v1.RelayAuth
	(*PunchRequest)(nil),    // 9: openair.v1.PunchRequest
	(*PunchReady)(nil),      // 10: openair.v1.PunchReady
}
var file_openair_v1_infra_proto_depIdxs = []int32{
	3, // 0: openair.v1.LookupResponse.registration:type_name -> openair.v1.Registration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_openair_v1_infra_proto_init() }
func file_openair_v1_infra_proto_init() {
	if File_openair_v1_infra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_infra_proto_rawDesc), len(file_openair_v1_infra_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_infra_proto_goTypes,
		DependencyIndexes: file_openair_v1_infra_proto_depIdxs,
		EnumInfos:         file_openair_v1_infra_proto_enumTypes,
		MessageInfos:      file_openair_v1_infra_proto_msgTypes,
	}.Build()
	File_openair_v1_infra_proto = out.File
	file_openair_v1_infra_proto_goTypes = nil
	file_openair_v1_infra_proto_depIdxs = nil
}
