// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/mirror.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Settled by measurement (D-84). Stream-per-frame with RESET_STREAM beat
// datagrams by three times at the median on a relayed path and lost no frames
// where datagrams lost one in thirty, because a keyframe is ~170 datagram
// fragments and any one of them takes the whole frame with it.
type MirrorMessageType int32

const (
	MirrorMessageType_MIRROR_MESSAGE_TYPE_UNSPECIFIED  MirrorMessageType = 0
	MirrorMessageType_MIRROR_MESSAGE_TYPE_START        MirrorMessageType = 1
	MirrorMessageType_MIRROR_MESSAGE_TYPE_STOP         MirrorMessageType = 2
	MirrorMessageType_MIRROR_MESSAGE_TYPE_REQUEST_IDR  MirrorMessageType = 3
	MirrorMessageType_MIRROR_MESSAGE_TYPE_BITRATE_HINT MirrorMessageType = 4
	MirrorMessageType_MIRROR_MESSAGE_TYPE_STATS        MirrorMessageType = 5
	MirrorMessageType_MIRROR_MESSAGE_TYPE_FRAME_HEADER MirrorMessageType = 6
)

// Enum value maps for MirrorMessageType.
var (
	MirrorMessageType_name = map[int32]string{
		0: "MIRROR_MESSAGE_TYPE_UNSPECIFIED",
		1: "MIRROR_MESSAGE_TYPE_START",
		2: "MIRROR_MESSAGE_TYPE_STOP",
		3: "MIRROR_MESSAGE_TYPE_REQUEST_IDR",
		4: "MIRROR_MESSAGE_TYPE_BITRATE_HINT",
		5: "MIRROR_MESSAGE_TYPE_STATS",
		6: "MIRROR_MESSAGE_TYPE_FRAME_HEADER",
	}
	MirrorMessageType_value = map[string]int32{
		"MIRROR_MESSAGE_TYPE_UNSPECIFIED":  0,
		"MIRROR_MESSAGE_TYPE_START":        1,
		"MIRROR_MESSAGE_TYPE_STOP":         2,
		"MIRROR_MESSAGE_TYPE_REQUEST_IDR":  3,
		"MIRROR_MESSAGE_TYPE_BITRATE_HINT": 4,
		"MIRROR_MESSAGE_TYPE_STATS":        5,
		"MIRROR_MESSAGE_TYPE_FRAME_HEADER": 6,
	}
)

func (x MirrorMessageType) Enum() *MirrorMessageType {
	p := new(MirrorMessageType)
	*p = x
	return p
}

func (x MirrorMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MirrorMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_mirror_proto_enumTypes[0].Descriptor()
}

func (MirrorMessageType) Type() protoreflect.EnumType {
	return &file_openair_v1_mirror_proto_enumTypes[0]
}

func (x MirrorMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MirrorMessageType.Descriptor instead.
func (MirrorMessageType) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_mirror_proto_rawDescGZIP(), []int{0}
}

// MirrorStart triggers the quiesce of flow.proto automatically: the source
// requests bulk throttling for the session's duration and releases on stop.
type MirrorStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Fps           uint32                 `protobuf:"varint,3,opt,name=fps,proto3" json:"fps,omitempty"`
	Codec         string                 `protobuf:"bytes,4,opt,name=codec,proto3" json:"codec,omitempty"`                              // "h264" initially
	MaxBitrate    uint32                 `protobuf:"varint,5,opt,name=max_bitrate,json=maxBitrate,proto3" json:"max_bitrate,omitempty"` // bytes/sec
	DisplayId     uint32                 `protobuf:"varint,6,opt,name=display_id,json=displayId,proto3" json:"display_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirrorStart) Reset() {
	*x = MirrorStart{}
	mi := &file_openair_v1_mirror_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorStart) ProtoMessage() {}

func (x *MirrorStart) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_mirror_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorStart.ProtoReflect.Descriptor instead.
func (*MirrorStart) Descriptor() ([]byte, []int) {
	return file_openair_v1_mirror_proto_rawDescGZIP(), []int{0}
}

func (x *MirrorStart) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MirrorStart) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MirrorStart) GetFps() uint32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *MirrorStart) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *MirrorStart) GetMaxBitrate() uint32 {
	if x != nil {
		return x.MaxBitrate
	}
	return 0
}

func (x *MirrorStart) GetDisplayId() uint32 {
	if x != nil {
		return x.DisplayId
	}
	return 0
}

type MirrorStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirrorStop) Reset() {
	*x = MirrorStop{}
	mi := &file_openair_v1_mirror_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorStop) ProtoMessage() {}

func (x *MirrorStop) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_mirror_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorStop.ProtoReflect.Descriptor instead.
func (*MirrorStop) Descriptor() ([]byte, []int) {
	return file_openair_v1_mirror_proto_rawDescGZIP(), []int{1}
}

type RequestIdr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestIdr) Reset() {
	*x = RequestIdr{}
	mi := &file_openair_v1_mirror_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestIdr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestIdr) ProtoMessage() {}

func (x *RequestIdr) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_mirror_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestIdr.ProtoReflect.Descriptor instead.
func (*RequestIdr) Descriptor() ([]byte, []int) {
	return file_openair_v1_mirror_proto_rawDescGZIP(), []int{2}
}

type BitrateHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesPerSec   uint32                 `protobuf:"varint,1,opt,name=bytes_per_sec,json=bytesPerSec,proto3" json:"bytes_per_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitrateHint) Reset() {
	*x = BitrateHint{}
	mi := &file_openair_v1_mirror_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitrateHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitrateHint) ProtoMessage() {}

func (x *BitrateHint) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_mirror_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitrateHint.ProtoReflect.Descriptor instead.
func (*BitrateHint) Descriptor() ([]byte, []int) {
	return file_openair_v1_mirror_proto_rawDescGZIP(), []int{3}
}

func (x *BitrateHint) GetBytesPerSec() uint32 {
	if x != nil {
		return x.BytesPerSec
	}
	return 0
}

type MirrorStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FramesDecoded uint32                 `protobuf:"varint,1,opt,name=frames_decoded,json=framesDecoded,proto3" json:"frames_decoded,omitempty"`
	FramesDropped uint32                 `protobuf:"varint,2,opt,name=frames_dropped,json=framesDropped,proto3" json:"frames_dropped,omitempty"`
	DecodeMsP95   uint32                 `protobuf:"varint,3,opt,name=decode_ms_p95,json=decodeMsP95,proto3" json:"decode_ms_p95,omitempty"`
	JitterMs      uint32                 `protobuf:"varint,4,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MirrorStats) Reset() {
	*x = MirrorStats{}
	mi := &file_openair_v1_mirror_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MirrorStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MirrorStats) ProtoMessage() {}

func (x *MirrorStats) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_mirror_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MirrorStats.ProtoReflect.Descriptor instead.
func (*MirrorStats) Descriptor() ([]byte, []int) {
	return file_openair_v1_mirror_proto_rawDescGZIP(), []int{4}
}

func (x *MirrorStats) GetFramesDecoded() uint32 {
	if x != nil {
		return x.FramesDecoded
	}
	return 0
}

func (x *MirrorStats) GetFramesDropped() uint32 {
	if x != nil {
		return x.FramesDropped
	}
	return 0
}

func (x *MirrorStats) GetDecodeMsP95() uint32 {
	if x != nil {
		return x.DecodeMsP95
	}
	return 0
}

func (x *MirrorStats) GetJitterMs() uint32 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

// FrameHeader opens each frame's own stream; the raw encoded frame follows,
// then a clean close. A frame that goes stale before it is fully sent is
// abandoned with RESET_STREAM rather than retransmitted.
type FrameHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	CapturedAt    int64                  `protobuf:"varint,2,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"` // source monotonic microseconds
	Keyframe      bool                   `protobuf:"varint,3,opt,name=keyframe,proto3" json:"keyframe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameHeader) Reset() {
	*x = FrameHeader{}
	mi := &file_openair_v1_mirror_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameHeader) ProtoMessage() {}

func (x *FrameHeader) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_mirror_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameHeader.ProtoReflect.Descriptor instead.
func (*FrameHeader) Descriptor() ([]byte, []int) {
	return file_openair_v1_mirror_proto_rawDescGZIP(), []int{5}
}

func (x *FrameHeader) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *FrameHeader) GetCapturedAt() int64 {
	if x != nil {
		return x.CapturedAt
	}
	return 0
}

func (x *FrameHeader) GetKeyframe() bool {
	if x != nil {
		return x.Keyframe
	}
	return false
}

var File_openair_v1_mirror_proto protoreflect.FileDescriptor

const file_openair_v1_mirror_proto_rawDesc = "" +
	"\n" +
	"\x17openair/v1/mirror.proto\x12\n" +
	"openair.v1\"\xa3\x01\n" +
	"\vMirrorStart\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x10\n" +
	"\x03fps\x18\x03 \x01(\rR\x03fps\x12\x14\n" +
	"\x05codec\x18\x04 \x01(\tR\x05codec\x12\x1f\n" +
	"\vmax_bitrate\x18\x05 \x01(\rR\n" +
	"maxBitrate\x12\x1d\n" +
	"\n" +
	"display_id\x18\x06 \x01(\rR\tdisplayId\"\f\n" +
	"\n" +
	"MirrorStop\"\f\n" +
	"\n" +
	"RequestIdr\"1\n" +
	"\vBitrateHint\x12\"\n" +
	"\rbytes_per_sec\x18\x01 \x01(\rR\vbytesPerSec\"\x9c\x01\n" +
	"\vMirrorStats\x12%\n" +
	"\x0eframes_decoded\x18\x01 \x01(\rR\rframesDecoded\x12%\n" +
	"\x0eframes_dropped\x18\x02 \x01(\rR\rframesDropped\x12\"\n" +
	"\rdecode_ms_p95\x18\x03 \x01(\rR\vdecodeMsP95\x12\x1b\n" +
	"\tjitter_ms\x18\x04 \x01(\rR\bjitterMs\"\\\n" +
	"\vFrameHeader\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1f\n" +
	"\vcaptured_at\x18\x02 \x01(\x03R\n" +
	"capturedAt\x12\x1a\n" +
	"\bkeyframe\x18\x03 \x01(\bR\bkeyframe*\x85\x02\n" +
	"\x11MirrorMessageType\x12#\n" +
	"\x1fMIRROR_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MIRROR_MESSAGE_TYPE_START\x10\x01\x12\x1c\n" +
	"\x18MIRROR_MESSAGE_TYPE_STOP\x10\x02\x12#\n" +
	"\x1fMIRROR_MESSAGE_TYPE_REQUEST_IDR\x10\x03\x12$\n" +
	" MIRROR_MESSAGE_TYPE_BITRATE_HINT\x10\x04\x12\x1d\n" +
	"\x19MIRROR_MESSAGE_TYPE_STATS\x10\x05\x12$\n" +
	" MIRROR_MESSAGE_TYPE_FRAME_HEADER\x10\x06BEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_mirror_proto_rawDescOnce sync.Once
	file_openair_v1_mirror_proto_rawDescData []byte
)

func file_openair_v1_mirror_proto_rawDescGZIP() []byte {
	file_openair_v1_mirror_proto_rawDescOnce.Do(func() {
		file_openair_v1_mirror_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_mirror_proto_rawDesc), len(file_openair_v1_mirror_proto_rawDesc)))
	})
	return file_openair_v1_mirror_proto_rawDescData
}

var file_openair_v1_mirror_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openair_v1_mirror_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_openair_v1_mirror_proto_goTypes = []any{
	(MirrorMessageType)(0), // 0: openair.v1.MirrorMessageType
	(*MirrorStart)(nil),    // 1: openair.v1.MirrorStart
	(*MirrorStop)(nil),     // 2: openair.v1.MirrorStop
	(*RequestIdr)(nil),     // 3: openair.v1.RequestIdr
	(*BitrateHint)(nil),    // 4: openair.v1.BitrateHint
	(*MirrorStats)(nil),    // 5: openair.v1.MirrorStats
	(*FrameHeader)(nil),    // 6: openair.v1.FrameHeader
}
var file_openair_v1_mirror_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openair_v1_mirror_proto_init() }
func file_openair_v1_mirror_proto_init() {
	if File_openair_v1_mirror_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_mirror_proto_rawDesc), len(file_openair_v1_mirror_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_mirror_proto_goTypes,
		DependencyIndexes: file_openair_v1_mirror_proto_depIdxs,
		EnumInfos:         file_openair_v1_mirror_proto_enumTypes,
		MessageInfos:      file_openair_v1_mirror_proto_msgTypes,
	}.Build()
	File_openair_v1_mirror_proto = out.File
	file_openair_v1_mirror_proto_goTypes = nil
	file_openair_v1_mirror_proto_depIdxs = nil
}
