// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/notifications.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationsMessageType int32

const (
	NotificationsMessageType_NOTIFICATIONS_MESSAGE_TYPE_UNSPECIFIED   NotificationsMessageType = 0
	NotificationsMessageType_NOTIFICATIONS_MESSAGE_TYPE_POSTED        NotificationsMessageType = 1
	NotificationsMessageType_NOTIFICATIONS_MESSAGE_TYPE_REMOVED       NotificationsMessageType = 2
	NotificationsMessageType_NOTIFICATIONS_MESSAGE_TYPE_DISMISS       NotificationsMessageType = 3
	NotificationsMessageType_NOTIFICATIONS_MESSAGE_TYPE_ACTION_INVOKE NotificationsMessageType = 4
)

// Enum value maps for NotificationsMessageType.
var (
	NotificationsMessageType_name = map[int32]string{
		0: "NOTIFICATIONS_MESSAGE_TYPE_UNSPECIFIED",
		1: "NOTIFICATIONS_MESSAGE_TYPE_POSTED",
		2: "NOTIFICATIONS_MESSAGE_TYPE_REMOVED",
		3: "NOTIFICATIONS_MESSAGE_TYPE_DISMISS",
		4: "NOTIFICATIONS_MESSAGE_TYPE_ACTION_INVOKE",
	}
	NotificationsMessageType_value = map[string]int32{
		"NOTIFICATIONS_MESSAGE_TYPE_UNSPECIFIED":   0,
		"NOTIFICATIONS_MESSAGE_TYPE_POSTED":        1,
		"NOTIFICATIONS_MESSAGE_TYPE_REMOVED":       2,
		"NOTIFICATIONS_MESSAGE_TYPE_DISMISS":       3,
		"NOTIFICATIONS_MESSAGE_TYPE_ACTION_INVOKE": 4,
	}
)

func (x NotificationsMessageType) Enum() *NotificationsMessageType {
	p := new(NotificationsMessageType)
	*p = x
	return p
}

func (x NotificationsMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationsMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_notifications_proto_enumTypes[0].Descriptor()
}

func (NotificationsMessageType) Type() protoreflect.EnumType {
	return &file_openair_v1_notifications_proto_enumTypes[0]
}

func (x NotificationsMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationsMessageType.Descriptor instead.
func (NotificationsMessageType) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_notifications_proto_rawDescGZIP(), []int{0}
}

// Posted mirrors a notification from source to sink. Per-app filtering happens
// on the *source* (PRD R22), before this message is constructed, so excluded
// content never crosses the wire and never reaches a relay. There is
// deliberately no filter-configuration message: putting filtering on the wire
// would mean the filtered content had already left the device.
type Posted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // opaque, stable, source-assigned
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	IconPng       []byte                 `protobuf:"bytes,6,opt,name=icon_png,json=iconPng,proto3" json:"icon_png,omitempty"` // sources should cap to 64x64
	PostedAt      int64                  `protobuf:"varint,7,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	Category      string                 `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"` // "msg" | "call" | "alarm" | "progress" | ""
	Actions       []*NotificationAction  `protobuf:"bytes,9,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posted) Reset() {
	*x = Posted{}
	mi := &file_openair_v1_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posted) ProtoMessage() {}

func (x *Posted) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posted.ProtoReflect.Descriptor instead.
func (*Posted) Descriptor() ([]byte, []int) {
	return file_openair_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Posted) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Posted) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Posted) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *Posted) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Posted) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Posted) GetIconPng() []byte {
	if x != nil {
		return x.IconPng
	}
	return nil
}

func (x *Posted) GetPostedAt() int64 {
	if x != nil {
		return x.PostedAt
	}
	return 0
}

func (x *Posted) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Posted) GetActions() []*NotificationAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type NotificationAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	AcceptsText   bool                   `protobuf:"varint,3,opt,name=accepts_text,json=acceptsText,proto3" json:"accepts_text,omitempty"` // inline reply
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationAction) Reset() {
	*x = NotificationAction{}
	mi := &file_openair_v1_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationAction) ProtoMessage() {}

func (x *NotificationAction) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationAction.ProtoReflect.Descriptor instead.
func (*NotificationAction) Descriptor() ([]byte, []int) {
	return file_openair_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationAction) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *NotificationAction) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *NotificationAction) GetAcceptsText() bool {
	if x != nil {
		return x.AcceptsText
	}
	return false
}

type Removed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Removed) Reset() {
	*x = Removed{}
	mi := &file_openair_v1_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Removed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Removed) ProtoMessage() {}

func (x *Removed) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Removed.ProtoReflect.Descriptor instead.
func (*Removed) Descriptor() ([]byte, []int) {
	return file_openair_v1_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *Removed) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Dismiss flows sink to source, giving dismiss-on-one-dismisses-everywhere.
// Sinks must tolerate a Removed for a key they never saw.
type Dismiss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dismiss) Reset() {
	*x = Dismiss{}
	mi := &file_openair_v1_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dismiss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dismiss) ProtoMessage() {}

func (x *Dismiss) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dismiss.ProtoReflect.Descriptor instead.
func (*Dismiss) Descriptor() ([]byte, []int) {
	return file_openair_v1_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *Dismiss) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ActionInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ActionId      string                 `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionInvoke) Reset() {
	*x = ActionInvoke{}
	mi := &file_openair_v1_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionInvoke) ProtoMessage() {}

func (x *ActionInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionInvoke.ProtoReflect.Descriptor instead.
func (*ActionInvoke) Descriptor() ([]byte, []int) {
	return file_openair_v1_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *ActionInvoke) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ActionInvoke) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActionInvoke) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_openair_v1_notifications_proto protoreflect.FileDescriptor

const file_openair_v1_notifications_proto_rawDesc = "" +
	"\n" +
	"\x1eopenair/v1/notifications.proto\x12\n" +
	"openair.v1\"\x84\x02\n" +
	"\x06Posted\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x19\n" +
	"\bicon_png\x18\x06 \x01(\fR\aiconPng\x12\x1b\n" +
	"\tposted_at\x18\a \x01(\x03R\bpostedAt\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x128\n" +
	"\aactions\x18\t \x03(\v2\x1e.openair.v1.NotificationActionR\aactions\"j\n" +
	"\x12NotificationAction\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12!\n" +
	"\faccepts_text\x18\x03 \x01(\bR\vacceptsText\"\x1b\n" +
	"\aRemoved\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x1b\n" +
	"\aDismiss\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"Q\n" +
	"\fActionInvoke\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text*\xeb\x01\n" +
	"\x18NotificationsMessageType\x12*\n" +
	"&NOTIFICATIONS_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!NOTIFICATIONS_MESSAGE_TYPE_POSTED\x10\x01\x12&\n" +
	"\"NOTIFICATIONS_MESSAGE_TYPE_REMOVED\x10\x02\x12&\n" +
	"\"NOTIFICATIONS_MESSAGE_TYPE_DISMISS\x10\x03\x12,\n" +
	"(NOTIFICATIONS_MESSAGE_TYPE_ACTION_INVOKE\x10\x04BEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_notifications_proto_rawDescOnce sync.Once
	file_openair_v1_notifications_proto_rawDescData []byte
)

func file_openair_v1_notifications_proto_rawDescGZIP() []byte {
	file_openair_v1_notifications_proto_rawDescOnce.Do(func() {
		file_openair_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_notifications_proto_rawDesc), len(file_openair_v1_notifications_proto_rawDesc)))
	})
	return file_openair_v1_notifications_proto_rawDescData
}

var file_openair_v1_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openair_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_openair_v1_notifications_proto_goTypes = []any{
	(NotificationsMessageType)(0), // 0: openair.v1.NotificationsMessageType
	(*Posted)(nil),                // 1: openair.v1.Posted
	(*NotificationAction)(nil),    // 2: openair.v1.NotificationAction
	(*Removed)(nil),               // 3: openair.v1.Removed
	(*Dismiss)(nil),               // 4: openair.v1.Dismiss
	(*ActionInvoke)(nil),          // 5: openair.v1.ActionInvoke
}
var file_openair_v1_notifications_proto_depIdxs = []int32{
	2, // 0: openair.v1.Posted.actions:type_name -> openair.v1.NotificationAction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_openair_v1_notifications_proto_init() }
func file_openair_v1_notifications_proto_init() {
	if File_openair_v1_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_notifications_proto_rawDesc), len(file_openair_v1_notifications_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_notifications_proto_goTypes,
		DependencyIndexes: file_openair_v1_notifications_proto_depIdxs,
		EnumInfos:         file_openair_v1_notifications_proto_enumTypes,
		MessageInfos:      file_openair_v1_notifications_proto_msgTypes,
	}.Build()
	File_openair_v1_notifications_proto = out.File
	file_openair_v1_notifications_proto_goTypes = nil
	file_openair_v1_notifications_proto_depIdxs = nil
}
