// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/pairing.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PairOffer travels out of band, in a QR code or a manually entered short code.
// It authenticates A to B only; the short authentication string in PairRequest
// and PairResponse is what authenticates B to A.
type PairOffer struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DeviceId            string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	IdentityFingerprint []byte                 `protobuf:"bytes,2,opt,name=identity_fingerprint,json=identityFingerprint,proto3" json:"identity_fingerprint,omitempty"` // SHA-256(identity_public_key)[0:16]
	LanHints            []string               `protobuf:"bytes,3,rep,name=lan_hints,json=lanHints,proto3" json:"lan_hints,omitempty"`                                  // "host:port" candidates
	ProtoVersion        uint32                 `protobuf:"varint,4,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PairOffer) Reset() {
	*x = PairOffer{}
	mi := &file_openair_v1_pairing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairOffer) ProtoMessage() {}

func (x *PairOffer) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_pairing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairOffer.ProtoReflect.Descriptor instead.
func (*PairOffer) Descriptor() ([]byte, []int) {
	return file_openair_v1_pairing_proto_rawDescGZIP(), []int{0}
}

func (x *PairOffer) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PairOffer) GetIdentityFingerprint() []byte {
	if x != nil {
		return x.IdentityFingerprint
	}
	return nil
}

func (x *PairOffer) GetLanHints() []string {
	if x != nil {
		return x.LanHints
	}
	return nil
}

func (x *PairOffer) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

// PairRequest and PairResponse carry both public keys per D-20. They are
// structurally identical but kept distinct so the transcript in PROTOCOL.md
// section 5.2 can order the nonces by role.
type PairRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdentityPublicKey  []byte                 `protobuf:"bytes,1,opt,name=identity_public_key,json=identityPublicKey,proto3" json:"identity_public_key,omitempty"`    // 32 bytes
	PrivilegePublicKey []byte                 `protobuf:"bytes,2,opt,name=privilege_public_key,json=privilegePublicKey,proto3" json:"privilege_public_key,omitempty"` // 32 bytes
	DisplayName        string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Platform           string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Nonce              []byte                 `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"` // 32 random bytes
	ProtectionTier     ProtectionTier         `protobuf:"varint,6,opt,name=protection_tier,json=protectionTier,proto3,enum=openair.v1.ProtectionTier" json:"protection_tier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PairRequest) Reset() {
	*x = PairRequest{}
	mi := &file_openair_v1_pairing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairRequest) ProtoMessage() {}

func (x *PairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_pairing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairRequest.ProtoReflect.Descriptor instead.
func (*PairRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_pairing_proto_rawDescGZIP(), []int{1}
}

func (x *PairRequest) GetIdentityPublicKey() []byte {
	if x != nil {
		return x.IdentityPublicKey
	}
	return nil
}

func (x *PairRequest) GetPrivilegePublicKey() []byte {
	if x != nil {
		return x.PrivilegePublicKey
	}
	return nil
}

func (x *PairRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PairRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PairRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PairRequest) GetProtectionTier() ProtectionTier {
	if x != nil {
		return x.ProtectionTier
	}
	return ProtectionTier_PROTECTION_TIER_UNSPECIFIED
}

type PairResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdentityPublicKey  []byte                 `protobuf:"bytes,1,opt,name=identity_public_key,json=identityPublicKey,proto3" json:"identity_public_key,omitempty"`
	PrivilegePublicKey []byte                 `protobuf:"bytes,2,opt,name=privilege_public_key,json=privilegePublicKey,proto3" json:"privilege_public_key,omitempty"`
	DisplayName        string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Platform           string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Nonce              []byte                 `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ProtectionTier     ProtectionTier         `protobuf:"varint,6,opt,name=protection_tier,json=protectionTier,proto3,enum=openair.v1.ProtectionTier" json:"protection_tier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PairResponse) Reset() {
	*x = PairResponse{}
	mi := &file_openair_v1_pairing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairResponse) ProtoMessage() {}

func (x *PairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_pairing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairResponse.ProtoReflect.Descriptor instead.
func (*PairResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_pairing_proto_rawDescGZIP(), []int{2}
}

func (x *PairResponse) GetIdentityPublicKey() []byte {
	if x != nil {
		return x.IdentityPublicKey
	}
	return nil
}

func (x *PairResponse) GetPrivilegePublicKey() []byte {
	if x != nil {
		return x.PrivilegePublicKey
	}
	return nil
}

func (x *PairResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PairResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PairResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PairResponse) GetProtectionTier() ProtectionTier {
	if x != nil {
		return x.ProtectionTier
	}
	return ProtectionTier_PROTECTION_TIER_UNSPECIFIED
}

// PairConfirm is sent by both peers after the user has compared the six-digit
// short authentication string on each device. Pairing completes only when both
// send accepted = true.
type PairConfirm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairConfirm) Reset() {
	*x = PairConfirm{}
	mi := &file_openair_v1_pairing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairConfirm) ProtoMessage() {}

func (x *PairConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_pairing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairConfirm.ProtoReflect.Descriptor instead.
func (*PairConfirm) Descriptor() ([]byte, []int) {
	return file_openair_v1_pairing_proto_rawDescGZIP(), []int{3}
}

func (x *PairConfirm) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_openair_v1_pairing_proto protoreflect.FileDescriptor

const file_openair_v1_pairing_proto_rawDesc = "" +
	"\n" +
	"\x18openair/v1/pairing.proto\x12\n" +
	"openair.v1\x1a\x17openair/v1/common.proto\"\x9d\x01\n" +
	"\tPairOffer\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x121\n" +
	"\x14identity_fingerprint\x18\x02 \x01(\fR\x13identityFingerprint\x12\x1b\n" +
	"\tlan_hints\x18\x03 \x03(\tR\blanHints\x12#\n" +
	"\rproto_version\x18\x04 \x01(\rR\fprotoVersion\"\x89\x02\n" +
	"\vPairRequest\x12.\n" +
	"\x13identity_public_key\x18\x01 \x01(\fR\x11identityPublicKey\x120\n" +
	"\x14privilege_public_key\x18\x02 \x01(\fR\x12privilegePublicKey\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\x12C\n" +
	"\x0fprotection_tier\x18\x06 \x01(\x0e2\x1a.openair.v1.ProtectionTierR\x0eprotectionTier\"\x8a\x02\n" +
	"\fPairResponse\x12.\n" +
	"\x13identity_public_key\x18\x01 \x01(\fR\x11identityPublicKey\x120\n" +
	"\x14privilege_public_key\x18\x02 \x01(\fR\x12privilegePublicKey\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\x12C\n" +
	"\x0fprotection_tier\x18\x06 \x01(\x0e2\x1a.openair.v1.ProtectionTierR\x0eprotectionTier\")\n" +
	"\vPairConfirm\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\bacceptedBEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_pairing_proto_rawDescOnce sync.Once
	file_openair_v1_pairing_proto_rawDescData []byte
)

func file_openair_v1_pairing_proto_rawDescGZIP() []byte {
	file_openair_v1_pairing_proto_rawDescOnce.Do(func() {
		file_openair_v1_pairing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_pairing_proto_rawDesc), len(file_openair_v1_pairing_proto_rawDesc)))
	})
	return file_openair_v1_pairing_proto_rawDescData
}

var file_openair_v1_pairing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_openair_v1_pairing_proto_goTypes = []any{
	(*PairOffer)(nil),    // 0: openair.v1.PairOffer
	(*PairRequest)(nil),  // 1: openair.v1.PairRequest
	(*PairResponse)(nil), // 2: openair.v1.PairResponse
	(*PairConfirm)(nil),  // 3: openair.v1.PairConfirm
	(ProtectionTier)(0),  // 4: openair.v1.ProtectionTier
}
var file_openair_v1_pairing_proto_depIdxs = []int32{
	4, // 0: openair.v1.PairRequest.protection_tier:type_name -> openair.v1.ProtectionTier
	4, // 1: openair.v1.PairResponse.protection_tier:type_name -> openair.v1.ProtectionTier
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_openair_v1_pairing_proto_init() }
func file_openair_v1_pairing_proto_init() {
	if File_openair_v1_pairing_proto != nil {
		return
	}
	file_openair_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_pairing_proto_rawDesc), len(file_openair_v1_pairing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_pairing_proto_goTypes,
		DependencyIndexes: file_openair_v1_pairing_proto_depIdxs,
		MessageInfos:      file_openair_v1_pairing_proto_msgTypes,
	}.Build()
	File_openair_v1_pairing_proto = out.File
	file_openair_v1_pairing_proto_goTypes = nil
	file_openair_v1_pairing_proto_depIdxs = nil
}
