// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/remotefs.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemotefsMessageType int32

const (
	RemotefsMessageType_REMOTEFS_MESSAGE_TYPE_UNSPECIFIED    RemotefsMessageType = 0
	RemotefsMessageType_REMOTEFS_MESSAGE_TYPE_STAT_REQUEST   RemotefsMessageType = 1
	RemotefsMessageType_REMOTEFS_MESSAGE_TYPE_STAT_RESPONSE  RemotefsMessageType = 2
	RemotefsMessageType_REMOTEFS_MESSAGE_TYPE_LIST_REQUEST   RemotefsMessageType = 3
	RemotefsMessageType_REMOTEFS_MESSAGE_TYPE_LIST_RESPONSE  RemotefsMessageType = 4
	RemotefsMessageType_REMOTEFS_MESSAGE_TYPE_READ_REQUEST   RemotefsMessageType = 5
	RemotefsMessageType_REMOTEFS_MESSAGE_TYPE_READ_RESPONSE  RemotefsMessageType = 6
	RemotefsMessageType_REMOTEFS_MESSAGE_TYPE_THUMB_REQUEST  RemotefsMessageType = 7
	RemotefsMessageType_REMOTEFS_MESSAGE_TYPE_THUMB_RESPONSE RemotefsMessageType = 8
)

// Enum value maps for RemotefsMessageType.
var (
	RemotefsMessageType_name = map[int32]string{
		0: "REMOTEFS_MESSAGE_TYPE_UNSPECIFIED",
		1: "REMOTEFS_MESSAGE_TYPE_STAT_REQUEST",
		2: "REMOTEFS_MESSAGE_TYPE_STAT_RESPONSE",
		3: "REMOTEFS_MESSAGE_TYPE_LIST_REQUEST",
		4: "REMOTEFS_MESSAGE_TYPE_LIST_RESPONSE",
		5: "REMOTEFS_MESSAGE_TYPE_READ_REQUEST",
		6: "REMOTEFS_MESSAGE_TYPE_READ_RESPONSE",
		7: "REMOTEFS_MESSAGE_TYPE_THUMB_REQUEST",
		8: "REMOTEFS_MESSAGE_TYPE_THUMB_RESPONSE",
	}
	RemotefsMessageType_value = map[string]int32{
		"REMOTEFS_MESSAGE_TYPE_UNSPECIFIED":    0,
		"REMOTEFS_MESSAGE_TYPE_STAT_REQUEST":   1,
		"REMOTEFS_MESSAGE_TYPE_STAT_RESPONSE":  2,
		"REMOTEFS_MESSAGE_TYPE_LIST_REQUEST":   3,
		"REMOTEFS_MESSAGE_TYPE_LIST_RESPONSE":  4,
		"REMOTEFS_MESSAGE_TYPE_READ_REQUEST":   5,
		"REMOTEFS_MESSAGE_TYPE_READ_RESPONSE":  6,
		"REMOTEFS_MESSAGE_TYPE_THUMB_REQUEST":  7,
		"REMOTEFS_MESSAGE_TYPE_THUMB_RESPONSE": 8,
	}
)

func (x RemotefsMessageType) Enum() *RemotefsMessageType {
	p := new(RemotefsMessageType)
	*p = x
	return p
}

func (x RemotefsMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemotefsMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_remotefs_proto_enumTypes[0].Descriptor()
}

func (RemotefsMessageType) Type() protoreflect.EnumType {
	return &file_openair_v1_remotefs_proto_enumTypes[0]
}

func (x RemotefsMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemotefsMessageType.Descriptor instead.
func (RemotefsMessageType) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_remotefs_proto_rawDescGZIP(), []int{0}
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_openair_v1_remotefs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_remotefs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_remotefs_proto_rawDescGZIP(), []int{0}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// StatResponse wraps FileStat so the response has a distinct message type.
// PROTOCOL.md section 11.1 named FileStat as both the structure and the
// response, leaving StatRequest without a declared counterpart.
type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          *FileStat              `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_openair_v1_remotefs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_remotefs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_remotefs_proto_rawDescGZIP(), []int{1}
}

func (x *StatResponse) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_openair_v1_remotefs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_remotefs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_remotefs_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileStat            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"` // more remain; re-request at a higher offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_openair_v1_remotefs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_remotefs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_remotefs_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetEntries() []*FileStat {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type FileStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedAt    int64                  `protobuf:"varint,3,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Mode          uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"` // POSIX permission bits, best-effort on Windows
	Mime          string                 `protobuf:"bytes,6,opt,name=mime,proto3" json:"mime,omitempty"`  // sniffed by the source, advisory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStat) Reset() {
	*x = FileStat{}
	mi := &file_openair_v1_remotefs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStat) ProtoMessage() {}

func (x *FileStat) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_remotefs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStat.ProtoReflect.Descriptor instead.
func (*FileStat) Descriptor() ([]byte, []int) {
	return file_openair_v1_remotefs_proto_rawDescGZIP(), []int{4}
}

func (x *FileStat) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileStat) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileStat) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *FileStat) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileStat) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileStat) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

// ReadRequest is sent once per stream; the source replies with a ReadResponse
// envelope followed by raw bytes. One request per stream lets several reads
// proceed without head-of-line blocking between them.
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_openair_v1_remotefs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_remotefs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_remotefs_proto_rawDescGZIP(), []int{5}
}

func (x *ReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Offset uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// May be shorter than requested, at end of file or because the source chose
	// a smaller quantum. Clients must handle short reads.
	Length        uint64 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Eof           bool   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_openair_v1_remotefs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_remotefs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_remotefs_proto_rawDescGZIP(), []int{6}
}

func (x *ReadResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadResponse) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ReadResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type ThumbRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MaxDimension  uint32                 `protobuf:"varint,2,opt,name=max_dimension,json=maxDimension,proto3" json:"max_dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbRequest) Reset() {
	*x = ThumbRequest{}
	mi := &file_openair_v1_remotefs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbRequest) ProtoMessage() {}

func (x *ThumbRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_remotefs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbRequest.ProtoReflect.Descriptor instead.
func (*ThumbRequest) Descriptor() ([]byte, []int) {
	return file_openair_v1_remotefs_proto_rawDescGZIP(), []int{7}
}

func (x *ThumbRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ThumbRequest) GetMaxDimension() uint32 {
	if x != nil {
		return x.MaxDimension
	}
	return 0
}

type ThumbResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mime          string                 `protobuf:"bytes,1,opt,name=mime,proto3" json:"mime,omitempty"`
	Image         []byte                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbResponse) Reset() {
	*x = ThumbResponse{}
	mi := &file_openair_v1_remotefs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbResponse) ProtoMessage() {}

func (x *ThumbResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_remotefs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbResponse.ProtoReflect.Descriptor instead.
func (*ThumbResponse) Descriptor() ([]byte, []int) {
	return file_openair_v1_remotefs_proto_rawDescGZIP(), []int{8}
}

func (x *ThumbResponse) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *ThumbResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

var File_openair_v1_remotefs_proto protoreflect.FileDescriptor

const file_openair_v1_remotefs_proto_rawDesc = "" +
	"\n" +
	"\x19openair/v1/remotefs.proto\x12\n" +
	"openair.v1\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"8\n" +
	"\fStatResponse\x12(\n" +
	"\x04stat\x18\x01 \x01(\v2\x14.openair.v1.FileStatR\x04stat\"O\n" +
	"\vListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"\\\n" +
	"\fListResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.openair.v1.FileStatR\aentries\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"\x92\x01\n" +
	"\bFileStat\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1f\n" +
	"\vmodified_at\x18\x03 \x01(\x03R\n" +
	"modifiedAt\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12\x12\n" +
	"\x04mime\x18\x06 \x01(\tR\x04mime\"Q\n" +
	"\vReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\"P\n" +
	"\fReadResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"G\n" +
	"\fThumbRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rmax_dimension\x18\x02 \x01(\rR\fmaxDimension\"9\n" +
	"\rThumbResponse\x12\x12\n" +
	"\x04mime\x18\x01 \x01(\tR\x04mime\x12\x14\n" +
	"\x05image\x18\x02 \x01(\fR\x05image*\x82\x03\n" +
	"\x13RemotefsMessageType\x12%\n" +
	"!REMOTEFS_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"REMOTEFS_MESSAGE_TYPE_STAT_REQUEST\x10\x01\x12'\n" +
	"#REMOTEFS_MESSAGE_TYPE_STAT_RESPONSE\x10\x02\x12&\n" +
	"\"REMOTEFS_MESSAGE_TYPE_LIST_REQUEST\x10\x03\x12'\n" +
	"#REMOTEFS_MESSAGE_TYPE_LIST_RESPONSE\x10\x04\x12&\n" +
	"\"REMOTEFS_MESSAGE_TYPE_READ_REQUEST\x10\x05\x12'\n" +
	"#REMOTEFS_MESSAGE_TYPE_READ_RESPONSE\x10\x06\x12'\n" +
	"#REMOTEFS_MESSAGE_TYPE_THUMB_REQUEST\x10\a\x12(\n" +
	"$REMOTEFS_MESSAGE_TYPE_THUMB_RESPONSE\x10\bBEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_remotefs_proto_rawDescOnce sync.Once
	file_openair_v1_remotefs_proto_rawDescData []byte
)

func file_openair_v1_remotefs_proto_rawDescGZIP() []byte {
	file_openair_v1_remotefs_proto_rawDescOnce.Do(func() {
		file_openair_v1_remotefs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_remotefs_proto_rawDesc), len(file_openair_v1_remotefs_proto_rawDesc)))
	})
	return file_openair_v1_remotefs_proto_rawDescData
}

var file_openair_v1_remotefs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openair_v1_remotefs_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_openair_v1_remotefs_proto_goTypes = []any{
	(RemotefsMessageType)(0), // 0: openair.v1.RemotefsMessageType
	(*StatRequest)(nil),      // 1: openair.v1.StatRequest
	(*StatResponse)(nil),     // 2: openair.v1.StatResponse
	(*ListRequest)(nil),      // 3: openair.v1.ListRequest
	(*ListResponse)(nil),     // 4: openair.v1.ListResponse
	(*FileStat)(nil),         // 5: openair.v1.FileStat
	(*ReadRequest)(nil),      // 6: openair.v1.ReadRequest
	(*ReadResponse)(nil),     // 7: openair.v1.ReadResponse
	(*ThumbRequest)(nil),     // 8: openair.v1.ThumbRequest
	(*ThumbResponse)(nil),    // 9: openair.v1.ThumbResponse
}
var file_openair_v1_remotefs_proto_depIdxs = []int32{
	5, // 0: openair.v1.StatResponse.stat:type_name -> openair.v1.FileStat
	5, // 1: openair.v1.ListResponse.entries:type_name -> openair.v1.FileStat
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_openair_v1_remotefs_proto_init() }
func file_openair_v1_remotefs_proto_init() {
	if File_openair_v1_remotefs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_remotefs_proto_rawDesc), len(file_openair_v1_remotefs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_remotefs_proto_goTypes,
		DependencyIndexes: file_openair_v1_remotefs_proto_depIdxs,
		EnumInfos:         file_openair_v1_remotefs_proto_enumTypes,
		MessageInfos:      file_openair_v1_remotefs_proto_msgTypes,
	}.Build()
	File_openair_v1_remotefs_proto = out.File
	file_openair_v1_remotefs_proto_goTypes = nil
	file_openair_v1_remotefs_proto_depIdxs = nil
}
