// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openair/v1/session.proto

package openairv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ControlMessageType enumerates msgType values for capID 0 (control).
// PROTOCOL.md defines the envelope's msgType field but never enumerated its
// values; these are that enumeration.
type ControlMessageType int32

const (
	ControlMessageType_CONTROL_MESSAGE_TYPE_UNSPECIFIED      ControlMessageType = 0
	ControlMessageType_CONTROL_MESSAGE_TYPE_HELLO            ControlMessageType = 1
	ControlMessageType_CONTROL_MESSAGE_TYPE_PAIR_OFFER       ControlMessageType = 2
	ControlMessageType_CONTROL_MESSAGE_TYPE_PAIR_REQUEST     ControlMessageType = 3
	ControlMessageType_CONTROL_MESSAGE_TYPE_PAIR_RESPONSE    ControlMessageType = 4
	ControlMessageType_CONTROL_MESSAGE_TYPE_PAIR_CONFIRM     ControlMessageType = 5
	ControlMessageType_CONTROL_MESSAGE_TYPE_AUTH_PROOF       ControlMessageType = 6
	ControlMessageType_CONTROL_MESSAGE_TYPE_REVOKE           ControlMessageType = 7
	ControlMessageType_CONTROL_MESSAGE_TYPE_CAPABILITY_GRANT ControlMessageType = 8
	ControlMessageType_CONTROL_MESSAGE_TYPE_CONSENT_REQUEST  ControlMessageType = 9
	ControlMessageType_CONTROL_MESSAGE_TYPE_CONSENT_RESPONSE ControlMessageType = 10
	ControlMessageType_CONTROL_MESSAGE_TYPE_SESSION_ANNOUNCE ControlMessageType = 11
	ControlMessageType_CONTROL_MESSAGE_TYPE_SESSION_END      ControlMessageType = 12
	ControlMessageType_CONTROL_MESSAGE_TYPE_SESSION_KILL     ControlMessageType = 13
	ControlMessageType_CONTROL_MESSAGE_TYPE_QUIESCE_REQUEST  ControlMessageType = 14
	ControlMessageType_CONTROL_MESSAGE_TYPE_QUIESCE_RELEASE  ControlMessageType = 15
	ControlMessageType_CONTROL_MESSAGE_TYPE_PATH_INFO        ControlMessageType = 16
)

// Enum value maps for ControlMessageType.
var (
	ControlMessageType_name = map[int32]string{
		0:  "CONTROL_MESSAGE_TYPE_UNSPECIFIED",
		1:  "CONTROL_MESSAGE_TYPE_HELLO",
		2:  "CONTROL_MESSAGE_TYPE_PAIR_OFFER",
		3:  "CONTROL_MESSAGE_TYPE_PAIR_REQUEST",
		4:  "CONTROL_MESSAGE_TYPE_PAIR_RESPONSE",
		5:  "CONTROL_MESSAGE_TYPE_PAIR_CONFIRM",
		6:  "CONTROL_MESSAGE_TYPE_AUTH_PROOF",
		7:  "CONTROL_MESSAGE_TYPE_REVOKE",
		8:  "CONTROL_MESSAGE_TYPE_CAPABILITY_GRANT",
		9:  "CONTROL_MESSAGE_TYPE_CONSENT_REQUEST",
		10: "CONTROL_MESSAGE_TYPE_CONSENT_RESPONSE",
		11: "CONTROL_MESSAGE_TYPE_SESSION_ANNOUNCE",
		12: "CONTROL_MESSAGE_TYPE_SESSION_END",
		13: "CONTROL_MESSAGE_TYPE_SESSION_KILL",
		14: "CONTROL_MESSAGE_TYPE_QUIESCE_REQUEST",
		15: "CONTROL_MESSAGE_TYPE_QUIESCE_RELEASE",
		16: "CONTROL_MESSAGE_TYPE_PATH_INFO",
	}
	ControlMessageType_value = map[string]int32{
		"CONTROL_MESSAGE_TYPE_UNSPECIFIED":      0,
		"CONTROL_MESSAGE_TYPE_HELLO":            1,
		"CONTROL_MESSAGE_TYPE_PAIR_OFFER":       2,
		"CONTROL_MESSAGE_TYPE_PAIR_REQUEST":     3,
		"CONTROL_MESSAGE_TYPE_PAIR_RESPONSE":    4,
		"CONTROL_MESSAGE_TYPE_PAIR_CONFIRM":     5,
		"CONTROL_MESSAGE_TYPE_AUTH_PROOF":       6,
		"CONTROL_MESSAGE_TYPE_REVOKE":           7,
		"CONTROL_MESSAGE_TYPE_CAPABILITY_GRANT": 8,
		"CONTROL_MESSAGE_TYPE_CONSENT_REQUEST":  9,
		"CONTROL_MESSAGE_TYPE_CONSENT_RESPONSE": 10,
		"CONTROL_MESSAGE_TYPE_SESSION_ANNOUNCE": 11,
		"CONTROL_MESSAGE_TYPE_SESSION_END":      12,
		"CONTROL_MESSAGE_TYPE_SESSION_KILL":     13,
		"CONTROL_MESSAGE_TYPE_QUIESCE_REQUEST":  14,
		"CONTROL_MESSAGE_TYPE_QUIESCE_RELEASE":  15,
		"CONTROL_MESSAGE_TYPE_PATH_INFO":        16,
	}
)

func (x ControlMessageType) Enum() *ControlMessageType {
	p := new(ControlMessageType)
	*p = x
	return p
}

func (x ControlMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_openair_v1_session_proto_enumTypes[0].Descriptor()
}

func (ControlMessageType) Type() protoreflect.EnumType {
	return &file_openair_v1_session_proto_enumTypes[0]
}

func (x ControlMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlMessageType.Descriptor instead.
func (ControlMessageType) EnumDescriptor() ([]byte, []int) {
	return file_openair_v1_session_proto_rawDescGZIP(), []int{0}
}

// Hello is exchanged by both peers immediately after the QUIC handshake.
// Neither may send anything else until it has both sent and received one.
type Hello struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProtoVersion   uint32                 `protobuf:"varint,1,opt,name=proto_version,json=protoVersion,proto3" json:"proto_version,omitempty"`
	DeviceId       string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // must match the DeviceID derived from the TLS key
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Platform       string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"` // "linux" | "windows" | "android" | "darwin"
	Capabilities   []*Capability          `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ProtectionTier ProtectionTier         `protobuf:"varint,6,opt,name=protection_tier,json=protectionTier,proto3,enum=openair.v1.ProtectionTier" json:"protection_tier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_openair_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_openair_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetProtoVersion() uint32 {
	if x != nil {
		return x.ProtoVersion
	}
	return 0
}

func (x *Hello) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Hello) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Hello) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Hello) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Hello) GetProtectionTier() ProtectionTier {
	if x != nil {
		return x.ProtectionTier
	}
	return ProtectionTier_PROTECTION_TIER_UNSPECIFIED
}

// Capability advertises one capability and the highest version supported.
// The effective version is the lower of the two peers' values.
type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            CapabilityId           `protobuf:"varint,1,opt,name=id,proto3,enum=openair.v1.CapabilityId" json:"id,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_openair_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_openair_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_openair_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *Capability) GetId() CapabilityId {
	if x != nil {
		return x.Id
	}
	return CapabilityId_CAPABILITY_ID_UNSPECIFIED
}

func (x *Capability) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_openair_v1_session_proto protoreflect.FileDescriptor

const file_openair_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x18openair/v1/session.proto\x12\n" +
	"openair.v1\x1a\x17openair/v1/common.proto\"\x89\x02\n" +
	"\x05Hello\x12#\n" +
	"\rproto_version\x18\x01 \x01(\rR\fprotoVersion\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12:\n" +
	"\fcapabilities\x18\x05 \x03(\v2\x16.openair.v1.CapabilityR\fcapabilities\x12C\n" +
	"\x0fprotection_tier\x18\x06 \x01(\x0e2\x1a.openair.v1.ProtectionTierR\x0eprotectionTier\"P\n" +
	"\n" +
	"Capability\x12(\n" +
	"\x02id\x18\x01 \x01(\x0e2\x18.openair.v1.CapabilityIdR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion*\xab\x05\n" +
	"\x12ControlMessageType\x12$\n" +
	" CONTROL_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONTROL_MESSAGE_TYPE_HELLO\x10\x01\x12#\n" +
	"\x1fCONTROL_MESSAGE_TYPE_PAIR_OFFER\x10\x02\x12%\n" +
	"!CONTROL_MESSAGE_TYPE_PAIR_REQUEST\x10\x03\x12&\n" +
	"\"CONTROL_MESSAGE_TYPE_PAIR_RESPONSE\x10\x04\x12%\n" +
	"!CONTROL_MESSAGE_TYPE_PAIR_CONFIRM\x10\x05\x12#\n" +
	"\x1fCONTROL_MESSAGE_TYPE_AUTH_PROOF\x10\x06\x12\x1f\n" +
	"\x1bCONTROL_MESSAGE_TYPE_REVOKE\x10\a\x12)\n" +
	"%CONTROL_MESSAGE_TYPE_CAPABILITY_GRANT\x10\b\x12(\n" +
	"$CONTROL_MESSAGE_TYPE_CONSENT_REQUEST\x10\t\x12)\n" +
	"%CONTROL_MESSAGE_TYPE_CONSENT_RESPONSE\x10\n" +
	"\x12)\n" +
	"%CONTROL_MESSAGE_TYPE_SESSION_ANNOUNCE\x10\v\x12$\n" +
	" CONTROL_MESSAGE_TYPE_SESSION_END\x10\f\x12%\n" +
	"!CONTROL_MESSAGE_TYPE_SESSION_KILL\x10\r\x12(\n" +
	"$CONTROL_MESSAGE_TYPE_QUIESCE_REQUEST\x10\x0e\x12(\n" +
	"$CONTROL_MESSAGE_TYPE_QUIESCE_RELEASE\x10\x0f\x12\"\n" +
	"\x1eCONTROL_MESSAGE_TYPE_PATH_INFO\x10\x10BEZCgithub.com/shreyashsri79/openair/internal/wire/openair/v1;openairv1b\x06proto3"

var (
	file_openair_v1_session_proto_rawDescOnce sync.Once
	file_openair_v1_session_proto_rawDescData []byte
)

func file_openair_v1_session_proto_rawDescGZIP() []byte {
	file_openair_v1_session_proto_rawDescOnce.Do(func() {
		file_openair_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openair_v1_session_proto_rawDesc), len(file_openair_v1_session_proto_rawDesc)))
	})
	return file_openair_v1_session_proto_rawDescData
}

var file_openair_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openair_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_openair_v1_session_proto_goTypes = []any{
	(ControlMessageType)(0), // 0: openair.v1.ControlMessageType
	(*Hello)(nil),           // 1: openair.v1.Hello
	(*Capability)(nil),      // 2: openair.v1.Capability
	(ProtectionTier)(0),     // 3: openair.v1.ProtectionTier
	(CapabilityId)(0),       // 4: openair.v1.CapabilityId
}
var file_openair_v1_session_proto_depIdxs = []int32{
	2, // 0: openair.v1.Hello.capabilities:type_name -> openair.v1.Capability
	3, // 1: openair.v1.Hello.protection_tier:type_name -> openair.v1.ProtectionTier
	4, // 2: openair.v1.Capability.id:type_name -> openair.v1.CapabilityId
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_openair_v1_session_proto_init() }
func file_openair_v1_session_proto_init() {
	if File_openair_v1_session_proto != nil {
		return
	}
	file_openair_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openair_v1_session_proto_rawDesc), len(file_openair_v1_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openair_v1_session_proto_goTypes,
		DependencyIndexes: file_openair_v1_session_proto_depIdxs,
		EnumInfos:         file_openair_v1_session_proto_enumTypes,
		MessageInfos:      file_openair_v1_session_proto_msgTypes,
	}.Build()
	File_openair_v1_session_proto = out.File
	file_openair_v1_session_proto_goTypes = nil
	file_openair_v1_session_proto_depIdxs = nil
}
